testing_webpage/api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns = [
    url(r'^get[-_]public[-_]posts$', views.get_public_posts, name='get_public_posts'),
    url(r'^add[-_]messages$', views.add_messages, name='add_messages'),
    url(r'^save[-_]leads$', views.save_leads, name='save_leads'),
    url(r'^get[-_]leads[-_]to[-_]filter$', views.get_leads_to_filter, name='get_leads_to_filter'),
    url(r'^get[-_]domains[-_]to[-_]filter$', views.get_domains_to_filter, name='get_domains_to_filter'),

    # API v1
    url(r'^v1/register$', views.register, name='register'),
    url(r'^v1/get[-_]work[-_]areas', views.get_work_areas, name='get_work_areas'),
    url(r'^v1/get[-_]cities$', views.get_cities, name='get_cities'),
    url(r'^v1/get[-_]campaigns$', views.get_campaigns, name='get_campaigns'),
]

testing_webpage/beta_invite/urls.py
from django.conf.urls import url

from . import views

app_name = 'beta_invite'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^registro$', views.register, name='register'),
    url(r'^pruebas$', views.tests, name='tests'),
    url(r'^test[-_]result$', views.get_test_result, name='test_result'),
    url(r'^add[-_]cv$', views.add_cv, name='add_cv'),
    url(r'^add[-_]cv[-_]changes$', views.add_cv_changes),
    url(r'^additional[-_]info$', views.additional_info, name='additional_info'),
    url(r'^save[-_]partial[-_]additional[-_]info$', views.save_partial_additional_info, name='save_partial_additional_info'),
    url(r'^active[-_]campaigns$', views.active_campaigns, name='active_campaigns'),
    url(r'^security[-_]politics$', views.security_politics, name='security_politics'),
    url(r'^apply$', views.apply, name='apply'),
    url(r'^home$', views.home, name='home'),
    url(r'^upload-audio-file$', views.upload_audio_file, name='upload-audio-file'),
]

testing_webpage/business/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from business import views

app_name = 'business'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # LOGIN AND LOGOUT
    url(r'^login$', auth_views.login, {'template_name': 'business/login.html', 'extra_context': {'error_message': ''}},
        name='login'),
    url(r'^logout$', auth_views.logout, {'next_page': 'business:index'}, name='logout'),
    # CREATE CAMPAIGN
    url(r'^seleccion-gratis$', views.start, name='start'),
    url(r'^seleccion[-_]gratis[-_]enviar$', views.start_post, name='start_post'),
    # CREATE CAMPAIGN WHEN USER IS LOGGED
    url(r'^crear[-_]enviar$', views.create_post, name='create_post'),
    # BUSINESS USER LOGGED
    url(r'^campañas/(?P<business_user_id>\d+)$', views.business_campaigns, name='business_campaigns'),
    url(r'^resumen/(?P<campaign_id>\d+)$', views.summary, name='summary'),
    url(r'^online-demo$', views.online_demo, name='online_demo'),
    url(r'^tablero-de-control/(?P<business_user_id>\d+)/(?P<campaign_id>\d+)/(?P<state_name>.*)/$', views.dashboard, name='dashboard'),
    url(r'^tablero-de-control/(?P<campaign_id>\d+)/request-candidates$', views.request_candidates, name='request_candidates'),
    url(r'^perfil-del-candidato/(?P<candidate_id>\d+)$', views.candidate_profile, name='candidate_profile'),
    # CONTACT
    url(r'^contactanos$', views.contact_form, name='contact_form'),
    url(r'^contact[-_]form[-_]post$', views.contact_form_post, name='contact_form_post'),
    # START
    url(r'^get-work-area-requirement/(?P<work_area_id>\d+)$', views.get_work_area_requirement, name='get_work_area_requirement'),
    # PAYU
    url(r'payment[-_]confirmation$', views.payment_confirmation, name='payment_confirmation'),
    # DEMO SCHEDULED
    url(r'^demo[-_]scheduled$', views.demo_scheduled, name='demo_scheduled'),
    # SAVE CANDIDATE COMMENTS
    url(r'^save[-_]comments$', views.save_comments, name='save_comments'),
    # CHANGE CANDIDATE STATE
    url(r'^change[-_]state$', views.change_state, name='change_state'),

    # TODO: This search url should be deleted?
    url(r'^search$', views.search, name='search'),
    url(r'^results$', views.calculate_result, name='results'),
    url(r'^business[-_]signup$', views.business_signup, name='business_signup'),
    url(r'^home$', views.home, name='home'),
    # TODO: Worst hack ever, replace for something like: \?id=[0-9]+
    url(r'^results/(?P<pk>\d+)$', views.render_result, name='render_result'),
]

'''
url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    auth_views.password_reset_confirm, name='password_reset_confirm'),
url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
'''

testing_webpage/beta_invite/views.py
import os
import io
import wave

from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseBadRequest, HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render
from ipware.ip import get_ip
from user_agents import parse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.views.decorators.csrf import csrf_exempt
from decouple import config as CONFIG
from google.cloud import speech
from google.cloud.speech import enums
from google.cloud.speech import types

from datetime import datetime
import common
from beta_invite import constants as cts
from beta_invite import test_module, new_user_module
from beta_invite.models import User, Visitor, Campaign, BulletType, City, Question, Experience, EducationExperience, School, Company, EmailType
from dashboard.models import Candidate
from business.custom_user_creation_form import CustomUserCreationForm
from testing_webpage.models import CandidatePendingEmail


def get_drop_down_values(language_code):
    """
    Gets lists of drop down values for several different fields.
    Args:
        language_code: 2 digit code (eg. 'es')
    Returns: A tuple containing (Countries, Education, Professions)
    """

    countries = common.get_countries()
    cities = common.get_cities()

    professions = common.get_professions(language_code)
    work_areas = common.get_work_areas(language_code)
    education = common.get_education(language_code)
    genders = common.get_genders(language_code)
    # TODO: add new drop down here

    return countries, cities, education, professions, work_areas, genders


def translate_bullets(bullets, lang_code):
    """
    Args:
        bullets: array with bullet Objects
        lang_code: 'es' for example
    Returns: translated array
    """
    a = []
    if lang_code == 'es':

        for b in bullets:
            b.name = b.name_es
            a.append(b)
    else:
        return bullets

    return a


def translate_tests(tests, lang_code):
    """
    Args:
        tests: array with test Objects
        lang_code: 'es' for example
    Returns: translated array
    """
    a = []
    if lang_code == 'es':

        for t in tests:
            t.name = t.name_es
            a.append(t)

        return a
    else:
        return tests


def get_index_params(request):

    # Gets information of client: such as if it is mobile
    is_desktop = not parse(request.META['HTTP_USER_AGENT']).is_mobile

    # If campaign_id is not found; will default to the default_campaign.
    campaign_id = request.GET.get('campaign_id', cts.DEFAULT_CAMPAIGN_ID)
    campaign = Campaign.objects.filter(pk=campaign_id).first()
    campaign.translate(request.LANGUAGE_CODE)

    ip = get_ip(request)

    Visitor(ip=ip, is_mobile=not is_desktop).save()

    perks = campaign.bullets.filter(bullet_type__in=BulletType.objects.filter(name='perk'))
    requirements = campaign.bullets.filter(bullet_type__in=BulletType.objects.filter(name='requirement'))

    if campaign.image is None:
        campaign.image = "default"
        campaign.save()

    param_dict = {'job_title': campaign.title,
                  'perks': translate_bullets(perks, request.LANGUAGE_CODE),
                  'requirements': translate_bullets(requirements, request.LANGUAGE_CODE),
                  'is_desktop': is_desktop,
                  'work_areas': common.get_work_areas(request.LANGUAGE_CODE),
                  'cities': common.get_cities(),
                  'default_city': common.get_city(request),
                  'image': campaign.image}

    if campaign_id is not None:
        param_dict['campaign_id'] = int(campaign_id)
        try:
            campaign = Campaign.objects.get(pk=int(campaign_id))
            campaign.translate(request.LANGUAGE_CODE)
            # if campaign exists send it.
            param_dict['campaign'] = campaign
        except ObjectDoesNotExist:
            pass

    return param_dict


def index(request):
    """
    will render a form to input user data.
    """
    return render(request, cts.INDEX_VIEW_PATH, get_index_params(request))


# TODO: refactor with the other method of same name in business/views
def get_first_error_message(form):
    """
    :param form: AuthenticationForm or UserCreationForm
    :return: str with first error_message
    """
    error_messages = [m[0] for m in form.errors.values()]
    if len(error_messages) > 0:  # Takes first element from the errors dictionary
        error_message = error_messages[0]
    else:
        error_message = 'unknown error'
    return error_message


def register(request):
    """
    Args:
        request: Request object
    Returns: Saves or updates the User, now it will not be creating new user objects for the same email.
    """

    signup_form = CustomUserCreationForm(request.POST)

    if signup_form.is_valid():

        # Gets information of client: such as if it is mobile.
        is_mobile = parse(request.META['HTTP_USER_AGENT']).is_mobile

        email = request.POST.get('username')
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        city_id = request.POST.get('city_id')
        work_area_id = request.POST.get('work_area_id')

        politics_accepted = request.POST.get('politics')
        if politics_accepted:
            politics = True
        else:
            politics = False
        campaign = common.get_campaign_from_request(request)

        # Validates all fields
        if campaign and name and phone and (email or not campaign.has_email):

            country = common.get_country_with_request(request)

            user_params = {'name': name,
                           'email': email,
                           'phone': phone,
                           'work_area_id': work_area_id,
                           'country': country,
                           'city': City.objects.get(pk=city_id),
                           'ip': get_ip(request),
                           'is_mobile': is_mobile,
                           'language_code': request.LANGUAGE_CODE,
                           'politics': politics}

            user = new_user_module.user_if_exists(email, phone, campaign)
            if user:
                user = new_user_module.update_user(campaign, user, user_params, request, signup_form=signup_form)
            else:
                user = new_user_module.create_user(campaign, user_params, request, is_mobile, signup_form=signup_form)

            return redirect('/servicio-de-empleo/pruebas?campaign_id={campaign_id}&user_id={user_id}'.format(campaign_id=campaign.id, user_id=user.id))
        else:
            return HttpResponseBadRequest('<h1>HTTP CODE 400: Client sent bad request with missing params</h1>')

    else:
        error_message = get_first_error_message(signup_form)
        params_dict = get_index_params(request)
        params_dict['error_message'] = error_message
        return render(request, cts.INDEX_VIEW_PATH, params_dict)


def apply(request):
    """
    When the user is logged in and applies to a second campaign
    :return:
    """

    user = User.get_user_from_request(request)
    campaign = common.get_campaign_from_request(request)

    candidate = new_user_module.candidate_if_exists(campaign, user)
    if not candidate:
        Candidate(campaign=campaign, user=user).save()

    return redirect('/servicio-de-empleo/pruebas?campaign_id={campaign_id}&user_id={user_id}'.format(
        campaign_id=campaign.id,
        user_id=user.id))


def tests(request):

    """
    Receives either GET or POST user and campaign ids.
    :param request: HTTP
    :return: renders tests.
    """

    campaign = common.get_campaign_from_request(request)
    user = common.get_user_from_request(request)
    candidate = common.get_candidate(user, campaign)

    tests = translate_tests(test_module.get_missing_tests(candidate, campaign), request.LANGUAGE_CODE)

    end_point_params = {'campaign_id': campaign.id,
                        'tests': tests}

    if not candidate:
        return redirect('/servicio-de-empleo?campaign_id={}'.format(campaign.id))
    if user is not None:
        end_point_params['user_id'] = int(user.id)  # Adds the user id to the params, to be able to track answers, later

    if tests:
        return render(request, cts.TESTS_VIEW_PATH, end_point_params)
    else:
        return redirect('/servicio-de-empleo/additional_info?candidate_id={candidate_id}'.format(candidate_id=candidate.pk))


def simple_login_and_user(login_form, request):
    """
    :param login_form: a AuthenticationForm object
    :param request: HTTP
    :return: BusinessUser obj
    """
    username = login_form.cleaned_data.get('username')
    password = login_form.cleaned_data.get('password')

    # Creates a Authentication user
    auth_user = authenticate(username=username,
                             password=password)

    login(request, auth_user)

    return User.objects.get(auth_user=auth_user)


def home(request):
    """
    Leads to Dashboard view.
    Args:
        request: HTTP request.
    Returns: displays all offers of a business
    """

    login_form = AuthenticationForm(data=request.POST)

    # TODO: generalize to set of blocked emails.
    if login_form.is_valid():

        try:
            user = simple_login_and_user(login_form, request)
        except ObjectDoesNotExist:
            # TODO: how to reload the exact campaign and at the same time pass on the error_message?
            return redirect('/trabajos')

        segment_code = user.get_work_area_segment_code()
        if segment_code:
            return redirect('/trabajos?segment_code={}'.format(segment_code))
        else:
            return redirect('/trabajos')

    else:
        error_message = get_first_error_message(login_form)
        # TODO: how to reload the exact page and at the same time pass on the error_message?

testing_webpage/beta_invite/templates/beta_invite/active_campaigns.html
{% extends 'base.html'%}
{% load i18n %}
{% load static %}


{% block title %}{% endblock %}

{% block extra_head %}

{% endblock %}

{% block content %}
    <br>
    <br>
    <div class="title" align="center" style="min-height:300px;font-family:var(--Bitter); color:var(--text-color)">
        <p style="font-size:40px; margin-bottom:60px;margin-top:60px;">Felicidades has diligenciado la información, pronto nos contáctaremos contigo</p>
    </div>

{% endblock %}

testing_webpage/beta_invite/templates/beta_invite/add_cv.html
{% extends 'base.html'%}
{% load i18n %}
{% load static %}


{% block title %}{% trans "PeakU" %}{% endblock %}

{% block extra_head %}

{% endblock %}


{% block content %}
   <!-- BEGIN WELCOME -->
    <div class="welcome-section" id="top" align="center">
      <div class="title">
        <br>

		  <div style="margin-top:55px;">

              <b style="color:#F8E676; font-size:25px; font-weight:400; text-transform: uppercase;">{% trans "Upload your resume" %}</b>
              <br>
              <br>

              <form action="add_cv_changes" method="post" style="text-align:center; margin-top:0px;" enctype="multipart/form-data">

                {% csrf_token %}

                  <input type="hidden" name="user_id" value="{{ user_id }}" />

                  <div style="margin-top:0px;">

                      <input style="font-family:Raleway; height: 30px; font-size: 12px; cursor:pointer; width:266px; margin: 0 auto;" type="file"
                        name="curriculum_url" id="curriculum" required="required">
                  </div>

                <br>

                {% trans "Sure!" as submit_value %}
                <input style="height: 44px; border: solid 0px white; background:#F8E676; color:black; text-align:center;
                 width: 81px; font-size: 16px; width: 250px; margin-bottom:40px; margin-top:5px; cursor:pointer;" type="submit" value="{{ submit_value }}">
                <br>
                <br>
                <br>
                <br>
              </form>
		  </div>
      </div>
    </div>
{% endblock %}

testing_webpage/beta_invite/templates/beta_invite/applied.html
{% extends 'peaku_base.html'%}
{% load i18n %}
{% load static %}


{% block title %}{% trans "PeakU - Test" %}{% endblock %}

{% block extra_head %}

{% endblock %}


{% block content %}
    <br>
    <br>
    <div class="title" align="center">

        {% if not tests %}
            <a class="scroll logo" style="font-family:CANDARA; font-size:65px; color:black;
             margin-bottom:50px;"> <img src="{% static 'beta_invite/logo.png' %}" width="370px" align="center"></a>
        {% endif %}

        <div class="container" align="center" style="margin-top:5px;">
            <div>
                {% if tests %}
                    <script>fbq('track', 'CompleteRegistration');</script>
                    <span>
                        <h1 style="color:var(--blue)">{% trans "Thanks for registering!" %}</h1>
                    </span>
                    <br>
                    {% include "beta_invite/test.html" with tests=tests %}
                {% else %}
                    <span style=" font-weight:500; color:#F8E676;">
                        <b style="font-weight:400; text-transform: uppercase; font-size:30px;">{% trans "Thanks for registering!" %}</b>
                    </span>
                    <br>
                    <b style="font-weight:400; color:#F8E676; font-size:18px">{% trans "We will contact you soon" %}</b>
                {% endif %}
            </div>
        </div>
        <br>
        <br>
    </div>
{% endblock %}

testing_webpage/beta_invite/templates/beta_invite/failed_test.html
{% extends 'base.html'%}
{% load i18n %}
{% load static %}


{% block title %}{% trans "PeakU - Test" %}{% endblock %}

{% block extra_head %}

{% endblock %}

{% block content %}
    <br>
    <br>
    <div class="title" align="center" style="font-family:var(--Bitter); color:var(--text-color)">
        <p style="font-size:40px; margin-bottom:60px;margin-top:20px;">{{ name }},</p>

        <p style="font-size:40px; margin-bottom:60px;margin-top:60px;">¡Bien hecho! Sin embargo aun puedes mejorar</p>

        <div style="font-size:18px;">
            <p>Te recomendamos Revisar este material y realizar de nuevo las pruebas</p>
            <br>
            <br>
            <ul>
                {% for score in failed_scores_with_feedback %}
                    <li>Apoyo en: <a href="{{ score.test.feedback_url }}">{{ score.test.name_es }}</a></li>
                {% endfor %}
            </ul>
            <br>
            <br>
            <form action="pruebas">
                <input type="hidden" name="user_id" value="{{ candidate.user.pk }}" />
                <input type="hidden" name="campaign_id" value="{{ candidate.campaign.pk }}" />
                <input id="submit-button" style="margin: 10px auto;" type="submit" value="¡ Repetir Pruebas !">
            </form>
        </div>
    </div>
    <br>
    <br>
    <style>
        #submit-button{
        width: auto;
        background: var(--orange);
        font-weight: bold;
        color: white;
        border: 0 none;
        border-radius: 1px;
        cursor: pointer;
        padding: 10px 10px;
        border-radius:4px;
    }
    </style>
{% endblock %}

testing_webpage/beta_invite/templates/beta_invite/index.html
{% extends 'transparent_header_base.html'%}
{% load static %}
{% load i18n %}
{% load app_filters %}
{% load compress %}
{% block title %}Agencia de empleo y trabajo{% endblock %}
{% block extra_meta %}
    <meta name="description"  content="En PeakU te ayudamos a encontrar el empleo que buscas en compañias que se ajustan a tu perfil, experiencia y salario. Somos una empresa que trabaja en selección de personal, no una temporal." />
    <meta name="keywords" content="computrabajo, servicio de empleo, empleo, empleos, trabajos, trabaja con nosotros, buscador de empleo, bolsa de empleo, agencia de empleo" />
{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'beta_invite/css/index.css' %}">
{% endblock %}
{% block extra_js %}
    <script type="text/javascript" src="{% static 'beta_invite/js/index.js' %}"></script>
{% endblock %}
{% block content %}
    <!----------------------------------------------SECTION 1---------------------------------------------------------->
    {% if user|user_is_authenticated %}
        <div class="row">
            <div class="col-lg-4 email-column">
                <a href=""></a>
                <form action="{% url 'beta_invite:apply' %}" method="post">
                    {% csrf_token %}
                    <input class="submit apply hide1" type="submit" value="APLICAR">
                    <input type="hidden" name="campaign_id" value="{{ campaign_id }}"/>
                </form>
            </div>
            <h2 class="descriptions">{% trans "GENERAL DESCRIPTION" %}</h2>
        </div>
        <div class="row">
            <div class="col-lg-8 description-text main-description">{% autoescape off %}{{ campaign.description }}{% endautoescape %}</div>
            <div class="col-lg-4 email-column">
                <form action="{% url 'beta_invite:apply' %}" method="post">
                    {% csrf_token %}
                    <input class="submit apply hide2" type="submit" value="APLICAR">
                    <input type="hidden" name="campaign_id" value="{{ campaign_id }}"/>
                </form>
            </div>
        </div>
    {% else %}
        <div class="row">
            <div class="col-lg-4 email-column">
                <input class="apply hide1" type="button" onclick="on_signup()" value="APLICAR">
            </div>
            <h2 class="descriptions">{% trans "GENERAL DESCRIPTION" %}</h2>
        </div>
        <div class="row">
            <div class="col-lg-8 description-text main-description">{% autoescape off %}{{ campaign.description }}{% endautoescape %}</div>
            <div class="col-lg-4 email-column">
                <input class="apply hide2" type="button" onclick="on_signup()" value="APLICAR">
            </div>
        </div>
    {% endif %}
    <div class="row">
        {% if campaign.city %}
            <h2 class="descriptions">Ciudad</h2>
        {% endif %}
    </div>
    <div class="row">
        <p class="description-text">{{ campaign.city.name }}</p>
    </div>
    {% if campaign.salary_low_range > 0 %}
        <div class="row">
            <h2 class="descriptions">Salario</h2>
        </div>
        <div class="row">
            <p class="description-text">
                {% if campaign.salary_low_range == campaign.salary_high_range %}
                    ${{ campaign.salary_low_range }}
                {% else %}
                    ${{ campaign.salary_low_range }} a ${{ campaign.salary_high_range }}
                {% endif %}
            </p>
        </div>
    {% endif %}
    <div class="row">
        {% if perks %}
            <h2 class="descriptions">{% trans "Perks" %}</h2>
        {% endif %}
    </div>
    <div class="row">
        <ul class="description-text">
            {% for perk in perks %}
                <li class="bullet">{{ perk.name }}</li>
            {% endfor %}
        </ul>
    </div>
    <div class="row">
        {% if requirements %}
            <h2 class="descriptions">{% trans "Requirements" %}</h2>
        {% endif %}
    </div>
    <div class="row final-row">
        <ul class="description-text">
            {% for req in requirements %}
                <li class="bullet">{{ req.name }}</li>
            {% endfor %}
        </ul>
    </div>
    <div id="overlay-login">
        <div id="form-image2">
            <form id="login-form" method="post" action="{% url 'beta_invite:home' %}" >
                {% csrf_token %}
                <fieldset>
                    <span class="exitDingbat" onclick="off_login()">X</span>
                    <br>
                    <br>
                    <span>Correo</span>
                    <input name="username" class="form-input"><br>
                    <span>Contraseña</span>
                    <input name="password" class="form-input" type="password"><br>
                    <span style="font-size:10px;"><a href="#" style="color:white">{% trans 'I forgot my password' %}</a></span>
                    <span style="font-size:10px">
                    <a href="javascript:void(0);" style="color:white" onclick="off_login() & on_signup()">{% trans "I'm not yet registered" %}
                    </a>
                    </span>
                    <br>
                    <br>
                    <input type="submit" class="submit" value="{% trans 'ACCESS' %}">
                </fieldset>
            </form>
        </div>
    </div>

    <div id="overlay-signup">
        <div class="form-image">
            <form class="only-register-form" action="{% url 'beta_invite:register' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset>
                <span class="exitDingbat" onclick="off_signup()">X</span>
                <br>
                <br>
                <input type="hidden" name="campaign_id" value="{{ campaign_id }}"/>
                <input type="hidden" name="candidate_id" value="{{ candidate.pk }}"/>

                <span>{% trans 'Your Full Name' %}</span>
                <input class="form-input" id="name" type="text" name="name" required="required" pattern="[A-Za-z\sáéíóúÑñÜüÁÉÍÓÚ]{1,200}">

                {% if campaign.has_email %}
                <span>{% trans 'Your email' %}</span>
                <input class="form-input" id="email" type="email" name="username" required="required">
                {% endif %}

                <span>{% trans 'Your phone' %}</span>
                <input class="form-input" id="phone" type="tel" name="phone" required="required" pattern="[0-9\(\)\+\-\s\.extension]{7,40}">

                <span>Ciudad de residencia</span>
                <select class="form-input white" name="city_id" >
                <option value="{{ default_city.id }}">{{ default_city.name }}</option>
                {% for city in cities %}
                <option value="{{ city.id }}">{{ city.name }}</option>
                {% endfor %}
                </select>
                <br>
                <span>Área de trabajo</span>
                <select class="form-input white" name="work_area_id" required>
                <option value="" selected disabled></option>
                {% for work_area in work_areas %}
                <option value="{{ work_area.id }}">{{ work_area.name }}</option>
                {% endfor %}
                </select>

                <input type="file" id="file" name="curriculum_url" class="form-inputfile" onchange="pressed()">
                <label for="file" id="fileLabel">{% trans "Upload your resume" %}</label>

                <div>
                    <label class="form-checkbox-container">
                        <span>Contraseña</span>
                    <input class="form-input" type="password" name="password1" required="required">
                    <br>
                    <span>Confirmar contraseña</span>
                    <input class="form-input" type="password" name="password2" required="required">
                    <br>
                    <input class="form-checkbox" type="checkbox" id="politics" name="politics" required>
                    <a href="security_politics" target="_blank"> He leído y acepto las políticas de privacidad</a>
                    </label>
                </div>
                <input class="submit" type="submit" id="submit" value="{% trans 'Sure!' %}">
                </fieldset>
                <span class="form-label register">¿Ya eres un usuario registrado? Inicia sesión
                    <a href="javascript:void(0);" onclick="off_signup() & on_login()"><strong>Aquí</strong></a>
                </span>
            </form>
        </div>
    </div>

    <script>
       $(document).ready(function() {
           set_background("{{ campaign.image }}", "main-section")
       });
    </script>
    <script>
        $( window ).resize(function() {
            set_background("{{ campaign.image }}", "main-section")
        });
    </script>

    <script>
        window.pressed = function(){
            var a = document.getElementById('file');
            if(a.value == "")
            {
                fileLabel.innerHTML = "Selecciona un archivo";
            }
            else
            {
                var theSplit = a.value.split('\\');
                fileLabel.innerHTML = theSplit[theSplit.length-1];
            }
        };
    </script>

    <script>
        function on_login() {
        $("#overlay-login").css("display", "block");
        $("#login-form").css("display", "block");
        $("html").css("background-size", "cover");
        $("nav").css("margin-bottom", "40px");

        if ($(window).width() < 769) {
            $("#login-form").animate({"marginLeft": 'auto'}, 650,"swing");
            $("#login-form").css("margin", "120px auto");
        }
        else {
            $("#login-form").animate({"marginLeft": '60%'}, 650,"swing");
            }
        }

        function off_login() {
        $("#overlay-login").css("display", "none");
        $("#login-form").css("display", "none");
        $("nav").css("margin-bottom", "");
        $("#login-form").animate({marginLeft: '160%'});
        }

        function on_signup() {
        $("#overlay-signup").css("display", "block");
        $(".only-register-form").css("display", "block");
        $("html").css("background-size", "cover");
        $("nav").css("margin-bottom", "40px");

        if ($(window).width() < 769) {
            $(".only-register-form").animate({"marginLeft": 'auto'}, 650,"swing");
            $(".only-register-form").css("margin", "120px auto");
            $(".register").css("margin-left", "30px");
        }
        else {
            $(".only-register-form").animate({"marginLeft": '60%'}, 650,"swing");
        }
        $(".form-image").animate({"backgroundPosition": '86%'}, 690,"swing");
        }

        function off_signup() {
        $("#overlay-signup").css("display", "none");
        $(".only-register-form").css("display", "none");
        $("nav").css("margin-bottom", "");
        $(".only-register-form").animate({marginLeft: '160%'});
        $(".form-image").animate({"backgroundPosition": '186%'}, 1,"swing");
        }
    </script>
    <!-- any incoming error_message will print as an alert-->
    <script>
        {% if error_message %}
            alert("{{ error_message }}");
        {% endif %}
    </script>
{% endblock %}