testing_webpage/api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns = [
    url(r'^get[-_]public[-_]posts$', views.get_public_posts, name='get_public_posts'),
    url(r'^add[-_]messages$', views.add_messages, name='add_messages'),
    url(r'^save[-_]leads$', views.save_leads, name='save_leads'),
    url(r'^get[-_]leads[-_]to[-_]filter$', views.get_leads_to_filter, name='get_leads_to_filter'),
    url(r'^get[-_]domains[-_]to[-_]filter$', views.get_domains_to_filter, name='get_domains_to_filter'),

    # API v1
    url(r'^v1/register$', views.register, name='register'),
    url(r'^v1/get[-_]work[-_]areas', views.get_work_areas, name='get_work_areas'),
    url(r'^v1/get[-_]cities$', views.get_cities, name='get_cities'),
    url(r'^v1/get[-_]campaigns$', views.get_campaigns, name='get_campaigns'),
]

testing_webpage/business/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from business import views

app_name = 'business'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # LOGIN AND LOGOUT
    url(r'^login$', auth_views.login, {'template_name': 'business/login.html', 'extra_context': {'error_message': ''}},
        name='login'),
    url(r'^logout$', auth_views.logout, {'next_page': 'business:index'}, name='logout'),
    # CREATE CAMPAIGN
    url(r'^seleccion-gratis$', views.start, name='start'),
    url(r'^seleccion[-_]gratis[-_]enviar$', views.start_post, name='start_post'),
    # CREATE CAMPAIGN WHEN USER IS LOGGED
    url(r'^crear[-_]enviar$', views.create_post, name='create_post'),
    # BUSINESS USER LOGGED
    url(r'^campañas/(?P<business_user_id>\d+)$', views.business_campaigns, name='business_campaigns'),
    url(r'^resumen/(?P<campaign_id>\d+)$', views.summary, name='summary'),
    url(r'^online-demo$', views.online_demo, name='online_demo'),
    url(r'^tablero-de-control/(?P<business_user_id>\d+)/(?P<campaign_id>\d+)/(?P<state_name>.*)/$', views.dashboard, name='dashboard'),
    url(r'^tablero-de-control/(?P<campaign_id>\d+)/request-candidates$', views.request_candidates, name='request_candidates'),
    url(r'^perfil-del-candidato/(?P<candidate_id>\d+)$', views.candidate_profile, name='candidate_profile'),
    # CONTACT
    url(r'^contactanos$', views.contact_form, name='contact_form'),
    url(r'^contact[-_]form[-_]post$', views.contact_form_post, name='contact_form_post'),
    # START
    url(r'^get-work-area-requirement/(?P<work_area_id>\d+)$', views.get_work_area_requirement, name='get_work_area_requirement'),
    # PAYU
    url(r'payment[-_]confirmation$', views.payment_confirmation, name='payment_confirmation'),
    # DEMO SCHEDULED
    url(r'^demo[-_]scheduled$', views.demo_scheduled, name='demo_scheduled'),
    # SAVE CANDIDATE COMMENTS
    url(r'^save[-_]comments$', views.save_comments, name='save_comments'),
    # CHANGE CANDIDATE STATE
    url(r'^change[-_]state$', views.change_state, name='change_state'),

    # TODO: This search url should be deleted?
    url(r'^search$', views.search, name='search'),
    url(r'^results$', views.calculate_result, name='results'),
    url(r'^business[-_]signup$', views.business_signup, name='business_signup'),
    url(r'^home$', views.home, name='home'),
    # TODO: Worst hack ever, replace for something like: \?id=[0-9]+
    url(r'^results/(?P<pk>\d+)$', views.render_result, name='render_result'),
]

'''
url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    auth_views.password_reset_confirm, name='password_reset_confirm'),
url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
'''

testing_webpage/dashboard/urls.py
from django.conf.urls import url

from . import views
from . import stats

app_name = 'dashboard'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # All tests
    url(r'^tests_list$', views.tests_list, name='tests_list'),

    # Campaign
    url(r'^campaign/(?P<campaign_id>\d+)$', views.edit_campaign_candidates, name='campaign'),
    url(r'^campaign/new$', views.new_campaign, name='new_campaign'),
    url(r'^campaign/create$', views.create_campaign, name='create_campaign'),
    url(r'^campaign/edit/(?P<campaign_id>\d+)$', views.edit_campaign, name='edit_campaign'),
    url(r'^campaign/update[-_]basic[-_]properties$', views.update_basic_properties),
    url(r'^campaign/delete/(?P<pk>\d+)$', views.delete_campaign, name='delete_campaign'),
    url(r'^campaign/candidate/(?P<candidate_id>\d+)$', views.candidate_detail, name='candidate_detail'),

    # Campaign tests
    url(r'^campaign/(?P<pk>\d+)/add[-_]test$', views.add_test),
    url(r'^campaign/(?P<pk>\d+)/delete[-_]test$', views.delete_test),
    url(r'^campaign/(?P<pk>\d+)/tests$', views.tests),

    # Test
    # url(r'^', include('home.urls', namespace='home')),
    url(r'^test/(?P<pk>\d+)$', views.edit_test, name='test_edit'),
    url(r'^test/new$', views.new_test, name='new_test'),
    url(r'^test/save$', views.save_test, name='save_test'),
    url(r'^test/update/(?P<pk>\d+)$', views.update_test, name='update_test'),
    url(r'^test/delete[-_]question$', views.delete_question, name='delete_question'),
    url(r'^test/delete[-_]answer$', views.delete_answer, name='delete_answer'),
    url(r'^test/duplicate/(?P<pk>\d+)$', views.duplicate_test, name='duplicate_test'),

    # Bullets
    url(r'^campaign/(?P<pk>\d+)/bullets$', views.bullets),
    url(r'^campaign/update[-_]bullets$', views.update_bullets),
    url(r'^campaign/delete[-_]bullet$', views.delete_bullet),

    # Interview
    url(r'^edit[-_]intro[-_]video$', views.edit_intro_video, name='edit_intro_video'),
    url(r'^campaign/interview/(?P<pk>\d+)$', views.interview, name='interview'),
    url(r'^campaign/check_interview$', views.check_interview, name='check_interview'),
    url(r'^campaign/interview/create[-_]interview[-_]question$', views.create_interview_question, name='create_interview_question'),
    url(r'^campaign/interview/update[-_]interview[-_]question$', views.update_interview_question, name='update_interview_question'),
    url(r'^campaign/interview/delete[-_]interview[-_]question$', views.delete_interview_question, name='delete_interview_question'),

    # Auto messenger
    url(r'^send[-_]new[-_]contacts$', views.send_new_contacts, name='send_new_contacts'),
    url(r'^send[-_]messages$', views.send_messages, name='send_messages'),

    # stats
    url(r'^candidates[-_]stats$', stats.candidate_count, name='candidates_stats'),
    url(r'^campaign[-_]stats$', stats.campaign_count, name='campaign_stats'),
    url(r'^number[-_]of[-_]forecasts$', stats.number_of_forecasts, name='number_of_forecasts'),
    url(r'^positive[-_]forecasts$', stats.positive_forecasts, name='positive_forecasts'),
    url(r'^negative[-_]forecasts$', stats.negative_forecasts, name='negative_forecasts'),
    url(r'^candidates[-_]per[-_]user$', stats.candidates_per_user, name='candidates_per_user'),
    url(r'^candidates[-_]from[-_]old[-_]users$', stats.candidates_from_old_users, name='candidates_from_old_users'),
    url(r'^stuck[-_]candidates$', stats.stuck_candidates, name='stuck_candidates'),
    url(r'^recommended[-_]candidates$', stats.recommended_candidates, name='recommended_candidates'),
    url(r'^paid-campaign-registrations$', stats.get_paid_campaign_registrations, name='paid_campaign_registrations'),
    url(r'^unique-users-registrations$', stats.get_unique_users_registrations, name='unique_users_registrations'),
]

testing_webpage/dashboard/views.py
import datetime
from django.core import serializers
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.db.models import Q
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

import basic_common
import common
from beta_invite.util import common_senders
from beta_invite import constants as beta_cts
from beta_invite.models import Campaign, Test, TestType, BulletType, Interview, Survey, Bullet, QuestionType, Question, Answer, CampaignState, CampaignMessage
from business.models import Company
from dashboard.models import Candidate, Message, Screening
from dashboard import constants as cts
from beta_invite.util import email_sender, messenger
from beta_invite.views import get_drop_down_values
from dashboard import interview_module, candidate_module, campaign_module, test_module
from match import model
from api.models import LeadMessage
from testing_webpage.models import CampaignPendingEmail, EmailType

CANDIDATE_FORECAST_LIMIT = 20


@login_required
def index(request):
    """
    Args:
        request: HTTP
    Returns: renders main view with a list of campaigns
    """

    # TODO: this basic login... works but the real admin users can be used instead
    # TODO: how to add the same auth to all the app????
    if basic_common.not_admin_user(request):
        return redirect('business:login')
    campaigns = Campaign.objects.filter(removed=False).order_by('-created_at', 'state', 'title_es').all()

    for campaign in campaigns:
        common.calculate_operational_efficiency(campaign)

    return render(request, cts.MAIN_DASHBOARD, {'campaigns': campaigns})

# ------------------------------- CAMPAIGN -------------------------------


def tests_list(request):
    """
    :param request: HTTP request
    :return: render view
    """

    tests = Test.get_all()

    return render(request, cts.TEST_LIST, {'tests': tests})


def candidate_detail(request, candidate_id):
    """
    :param request: HTTP request
    :param candidate_id: int Candidate id
    :return: render view
    """
    return render(request, cts.CANDIDATE_DETAIL, {'candidate': Candidate.objects.get(pk=candidate_id)})


def add_to_message_queue(candidates, text):
    """
    Adds objects to the message table. So later on this table will serve as a message queue.
    :param candidates: list of candidates.
    :param text: string
    :return: writes on table messages to be sent.
    """
    for candidate in candidates:
        Message(candidate=candidate, text=text).save()


def update_candidate_forecast(campaign):
    """
    Updates up to CANDIDATE_FORECAST_LIMIT per execution, due to time limit on production server, and possible crash.
    :return: updates.
    """
    candidates = Candidate.objects.filter(Q(match_classification=None) & Q(campaign=campaign)).all()
    candidates = candidates[:min(len(candidates), CANDIDATE_FORECAST_LIMIT)]
    model.predict_match_and_save(candidates)


# TODO: use Ajax to optimize rendering. Has no graphics therefore is very low priority.
def edit_campaign_candidates(request, campaign_id):
    """
    Args:
        request: HTTP
        campaign_id: campaign primary key
    Returns: This controls the candidates dashboard
    """
    campaign = Campaign.objects.get(pk=campaign_id)

    action = request.POST.get('action')
    candidate_id = request.POST.get('candidate_id')
    if candidate_id is not None:
        candidate = Candidate.objects.get(pk=int(candidate_id))

        if action == 'update':
            candidate_module.update_candidate_manually(request, candidate)
        elif action == 'add':
            candidate_module.add_candidate_to_campaign(request, candidate)
        elif action == 'remove':
            candidate_module.remove_candidate(candidate)
        elif action == 'move':
            if candidate_module.add_candidate_to_campaign(request, candidate):  # only erase if has add successfully
                candidate_module.remove_candidate(candidate)

    # TODO: can be done with JS in smarter way???
    # enters here when sending an email
    if request.POST.get('send_mail') is not None:

        candidates = candidate_module.get_checked_box_candidates(campaign_id, request)

        email_sender.send(objects=candidates,
                          language_code=request.LANGUAGE_CODE,
                          body_input=request.POST.get('email_body'),
                          subject=candidate_module.get_subject(request, campaign_id),
                          with_localization=False,
                          body_is_filename=False)

    if request.POST.get('send_message') is not None:
        candidates = candidate_module.get_checked_box_candidates(campaign_id, request)
        add_to_message_queue(candidates, request.POST.get('email_body'))

    update_candidate_forecast(campaign)

    params, states = candidate_module.get_rendering_data(campaign_id)

    # all campaigns except the current one.
    campaigns_to_move_to = Campaign.objects.exclude(pk=campaign_id)

    params['states'] = states
    params['campaign_id'] = campaign_id
    params['screenings'] = [s for s in Screening.objects.all()]
    params['campaigns'] = campaigns_to_move_to
    params['current_campaign'] = Campaign.objects.get(pk=campaign_id)

    return render(request, cts.EDIT_CANDIDATES, params)


def new_campaign(request):

    countries, cities, education, professions, work_areas, genders = get_drop_down_values(request.LANGUAGE_CODE)
    bullet_types_json = serializers.serialize("json", BulletType.objects.all())

    return render(request, cts.NEW_OR_EDIT_CAMPAIGN, {'countries': countries,
                                                      'education': education,
                                                      'professions': professions,
                                                      'bullet_types_json': bullet_types_json,
                                                      'action_url': '/dashboard/campaign/create',
                                                      'title': 'Nueva Campaña',
                                                      })


def create_campaign(request):
    """
    When you are in a new campaign and you save the model
    Args:
        request: HTTP
    Returns:
    """

    campaign_module.create_campaign(request)

    # in this specific case gotta go back. Because if the user stays modifying the campaign on the 'new' template it
    # will create additional campaigns instead of modifying the first creation.
    return redirect('/dashboard')


def edit_campaign(request, campaign_id):
    """
    Args:
        request: HTTP
        campaign_id: campaign_id
    Returns: Renders basic properties of a campaign
    """
    campaign = Campaign.objects.get(pk=campaign_id)
    countries, cities, education, professions, work_areas, genders = get_drop_down_values(request.LANGUAGE_CODE)
    business_user = common.get_business_user_with_campaign(campaign)
    if not business_user:
        company = ""
    else:
        company = business_user.company

    return render(request, cts.NEW_OR_EDIT_CAMPAIGN, {'countries': countries,
                                                      'cities': cities,
                                                      'education': education,
                                                      'professions': professions,
                                                      'work_areas': work_areas,
                                                      'campaign': campaign,
                                                      'action_url': '/dashboard/campaign/update_basic_properties',
                                                      'title': 'Update {}'.format(campaign.title_es),
                                                      'campaign_states': CampaignState.objects.all(),
                                                      'company': company
                                                      })


def send_feedback_message_and_mail(business_user, campaign, request):

    # goes from active to finish, will ask for feedback
    if campaign.state == CampaignState.objects.get(code='A') and \
                    int(request.POST.get('state_id')) == CampaignState.objects.get(code='F').id:

        # TODO: this is really wrong
        CampaignPendingEmail.add_to_queue(the_objects=campaign,
                                          language_code='es',
                                          body_input='business_feedback',
                                          subject='Publicación terminada {campaign}',
                                          email_type=EmailType.objects.get(name='business_feedback'))
        messenger.send(objects=campaign,
                       language_code='es',
                       body_input='business_feedback')


def update_basic_properties(request):
    """
    Args:
        request: HTTP.
    Returns: Updates just the basics of a campaign.
    """
    campaign = common.get_campaign_from_request(request)
    business_user = common.get_business_user_with_campaign(campaign)

    send_feedback_message_and_mail(business_user, campaign, request)

    campaign_module.update_campaign_basic_properties(campaign, request)
    if business_user:
        company = business_user.company
        if company:
            company.name = request.POST.get('company')
            company.save()
        else:
            company = Company()
            company.name = request.POST.get('company')
            company.save()
            business_user.company = company
            business_user.save()
    else:
        pass

    return campaign_module.get_campaign_edit_url(campaign)


def delete_campaign(request, pk):

    campaign = Campaign.objects.get(pk=pk)

    if campaign:
        campaign.removed = True
        campaign.save()

    return redirect('/dashboard')


# ------------------------------- CAMPAIGN TESTS -------------------------------

testing_webpage/dashboard/templates/dashboard/candidate_edit.html
<form action="../" method="post"
       enctype="multipart/form-data">
    {% csrf_token %}
    <input type="submit" value="HOME">
</form>


<h1>Candidates</h1>
<ul>

    <form action="#" method="post"
       enctype="multipart/form-data">

        {% csrf_token %}

        {% for candidate in candidates %}
            <li>{{ candidate.user.name }}:

                <input type="hidden" name="campaign_id" value="{{ candidate.campaign_id }}" />

                <br>

                <input style="width:25%" name="{{ candidate.id }}_comment" type="text"
                    value="{{ candidate.comment }}" placeholder="make any comment!">

                <br>

              <select name="{{ candidate.id }}_state" required>
                  <option value="{{ candidate.state_id}}">{{ candidate.state.name }}</option>
                  {% for state in states%}
                     <option value="{{ state.id }}">{{ state.name }}</option>
                  {% endfor %}
              </select>

            </li>

            <br>
        {% endfor %}

        <br>

        <input type="submit" value="Save Changes!">

    </form>
</ul>

<a href="new">Add Candidate</a>

testing_webpage/dashboard/templates/dashboard/edit.html
<!--TODO: put it on the head-->
{% load static %}

<head>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'js/edit.js' %}" async></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/edit.css' %}">

    <form action="../dashboard/" method="post"
           enctype="multipart/form-data">
        {% csrf_token %}
        <input type="submit" value="HOME">
    </form>

</head>

<body>

    <h1>{{ current_campaign.name }} Candidates</h1>
    <ul>

        <form action="#" method="post" id="main_form_id"
           enctype="multipart/form-data">

            {% csrf_token %}

                <div class="row" style="margin-top:45px;">

                    <div class="col-sm-4">

                        <h3>Backlog</h3>
                        <br>

                        {% for candidate in backlog %}
                            {% include "dashboard/candidate.html" with candidate=candidate campaigns=campaigns%}
                        {% endfor %}

                    </div>
                    <div class="col-sm-4">

                        <h3>Waiting for Tests</h3>
                        <br>

                        {% for candidate in waiting_tests %}
                            {% include "dashboard/candidate.html" with candidate=candidate campaigns=campaigns%}
                        {% endfor %}

                    </div>
                    <div class="col-sm-4">

                        <h3>Waiting for Interview</h3>
                        <br>

                        {% for candidate in waiting_interview %}
                            {% include "dashboard/candidate.html" with candidate=candidate campaigns=campaigns %}
                        {% endfor %}

                    </div>
                </div>

                <div class="row" style="margin-top:45px;">
                    <div class="col-sm-4">

                        <h3>Sent To Client</h3>
                        <br>

                        {% for candidate in sent_to_client %}
                            {% include "dashboard/candidate.html" with candidate=candidate campaigns=campaigns %}
                        {% endfor %}

                    </div>

                    <div class="col-sm-4">

                        <h3>Got Job</h3>
                        <br>

                        {% for candidate in got_job %}
                            {% include "dashboard/candidate.html" with candidate=candidate campaigns=campaigns %}
                        {% endfor %}

                    </div>
                    <div class="col-sm-4">

                        <h3>Rejected</h3>
                        <br>

                        {% for candidate in rejected %}
                            {% include "dashboard/candidate.html" with candidate=candidate campaigns=campaigns %}
                        {% endfor %}
                    </div>
                </div>

            <br>
            <br>
            <br>
            <br>
            <br>
            <hr>
            <br>
            <br>

            <h3>Send customized mail</h3>

            <input name="email_subject" style="width:32.5%"
                value="Status de tu aplicación a {campaign_name} con PeakU">{{ candidate.comment }}</input>

            <br>
            <br>

            <textarea name="email_body" cols="60" rows="20"
                placeholder="mail body, use tags {name}, {campaign_name} to customize" >
{name},

write here ... {test_url}

Saludos

Santiago
santiago@peaku.co
PeakU
            </textarea>

            <br>

            <input type="submit" name="send_mail" value="Send_email">

        </form>

    </ul>

    <a href="new">Add Candidate</a>


</body>

testing_webpage/dashboard/templates/dashboard/index.html
{% extends 'base.html'%}
{% load static %}
{% load i18n %}
{% load app_filters %}
{% load compress %}
{% block title %}DASHBOARD{% endblock %}
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/index.css' %}">
{% endblock %}
{% block content %}
<div class="row">
    <form action="{% url 'business:results' %}">
        <input style="width:500px;" id="search-input" type="text" name="search_text" placeholder="{% trans 'Search positions (eg android developer)' %}">
    </form>
</div>
<div class="row">
    <h2>Stats for nerds</h2>
    <p><a href="{% url 'dashboard:candidates_stats' %}" target="_blank">Total candidates per month</a></p>
    <p><a href="{% url 'dashboard:campaign_stats' %}" target="_blank">Total campaigns per month</a></p>
    <p><a href="{% url 'dashboard:number_of_forecasts' %}" target="_blank">Total Forecasts</a></p>
    <p><a href="{% url 'dashboard:positive_forecasts' %}" target="_blank">Positive Forecasts</a></p>
    <p><a href="{% url 'dashboard:negative_forecasts' %}" target="_blank">Negative Forecasts</a></p>
    <p><a href="{% url 'dashboard:candidates_per_user' %}" target="_blank">Candidates per User</a></p>
    <p><a href="{% url 'dashboard:candidates_from_old_users' %}" target="_blank">Candidates from old users</a></p>
    <p><a href="{% url 'dashboard:stuck_candidates' %}" target="_blank">Percentage of candidates in backlog or Prospect</a></p>
    <p><a href="{% url 'dashboard:recommended_candidates' %}" target="_blank">Total recommended candidates</a></p>
    <p><a href="{% url 'dashboard:paid_campaign_registrations' %}" target="_blank">Total paid campaigns</a></p>
    <p><a href="{% url 'dashboard:unique_users_registrations' %}" target="_blank">Unique user registrations</a></p>

    <p class="tests"><a href="{% url 'dashboard:tests_list' %}" target="_blank">Ver Pruebas</a></p>
    <h2 style="text-align:center; font-size:60px;">CAMPAÑAS</h2>
    <p><a href="campaign/new">Nueva campaña</a></p>
</div>
<div class="row">
    <div class="col-lg-6">
        <ul>
            <h2 class="center">PAGAS</h2>
            {% for campaign in campaigns %}
            {% if not campaign.free_trial %}
            <div class="campaign-div">
                <div class="row">
                    <p class="tittle">{{ campaign.title_es }}</p>
                <div class="col-lg-5">

                    <a href="{{ campaign|get_campaign_url }}" target="_blank">Ver publicación (long_form)</a>
                    <br>
                    <a href="{% url 'dashboard:campaign' campaign.id %}" target="_blank">Ver candidatos</a>
                    <br>
                    <a href="{% url 'dashboard:edit_campaign' campaign.id %}" target="_blank">Editar campaña</a>
                    <br>
                    <a href="{% url 'dashboard:campaign' campaign.id %}/bullets" target="_blank">Bullets</a>
                    <br>
                    <a href="{% url 'business:summary' campaign_id=campaign.id %}" target="_blank">Ver Dashboard Empresarial</a>
                    <br>
                    <a href="{% url 'dashboard:campaign' campaign.id %}/tests" target="_blank">Ver pruebas</a>
                    <br>
                    <br>
                    <form action="{% url 'dashboard:delete_campaign'  campaign.id %}" method="post">
                        {% csrf_token %}
                        <input type="button" class="btn btn-danger" value="Delete!" onclick="this.form.submit();">
                    </form>
                </div>
                <div class="col-lg-7">
                    <p><b>EMPRESA:</b> {{ campaign|get_business_user_company_with_campaign }}</p>
                    <p><b>REPRESENTANTE:</b> {{ campaign|get_business_user_name_with_campaign }}</p>
                    <p><b>ESTADO:</b> {{ campaign.state.name_es }}</p>
                    <p><b>FECHA DE CREACIÓN:</b> {{ campaign.local_date }}</p>
                    {% if campaign.operational_efficiency %}
                    <p><b>EFICIENCIA (STC/(STC + RECHAZADOS MANUALES)):</b> {% widthratio campaign.operational_efficiency 1 100 %}%</p>
                    {% endif %}
                </div>
                </div>
            </div>
            <br>
            {% endif %}
            {% endfor %}
        </ul>
    </div>
    <div class="col-lg-6">
        <ul>
            <h2 class="center">GRATIS</h2>
            {% for campaign in campaigns %}
            {% if campaign.free_trial %}
                <div class="campaign-div">
                <div class="row">
                    <p class="tittle">{{ campaign.title_es }}</p>
                <div class="col-lg-5">
                    <a href="{{ campaign|get_campaign_url }}" target="_blank">Ver publicación (long_form)</a>
                    <br>
                    <a href="{% url 'dashboard:campaign' campaign.id %}" target="_blank">Ver candidatos</a>
                    <br>
                    <a href="{% url 'dashboard:edit_campaign' campaign.id %}" target="_blank">Editar campaña</a>
                    <br>
                    <a href="{% url 'dashboard:campaign' campaign.id %}/bullets" target="_blank">Bullets</a>
                    <br>
                    <a href="{% url 'business:summary' campaign_id=campaign.id %}" target="_blank">Ver Dashboard Empresarial</a>
                    <br>
                    <a href="{% url 'dashboard:campaign' campaign.id %}/tests" target="_blank">Ver pruebas</a>
                    <br>
                    <br>
                    <form action="{% url 'dashboard:delete_campaign'  campaign.id %}" method="post">
                        {% csrf_token %}
                        <input type="button" class="btn btn-danger" value="Delete!" onclick="this.form.submit();">
                    </form>
                </div>
                <div class="col-lg-7">
                    <p><b>EMPRESA:</b> {{ campaign|get_business_user_company_with_campaign }}</p>
                    <p><b>REPRESENTANTE:</b> {{ campaign|get_business_user_name_with_campaign }}</p>
                    <p><b>ESTADO:</b> {{ campaign.state.name_es }}</p>
                    <p><b>FECHA DE CREACIÓN:</b> {{ campaign.local_date }}</p>
                    {% if campaign.operational_efficiency %}
                    <p><b>EFICIENCIA (STC/(STC + RECHAZADOS MANUALES)):</b> {% widthratio campaign.operational_efficiency 1 100 %}%</p>
                    {% endif %}
                </div>
                </div>
            </div>
            <br>
            {% endif %}
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

testing_webpage/dashboard/templates/dashboard/stats_index.html
<!DOCTYPE html>
<html>
<head>
	<title>stats</title>
	{% load static %}
	<script type="text/javascript" src="{% static 'fusioncharts/js/fusioncharts.js' %}"></script>
    <script type="text/javascript" src="{% static 'fusioncharts/js/themes/fusioncharts.theme.fint.js' %}"></script>
</head>
<body>
	<div id="chart-1">{{ output|safe }}</div>
</body>
</html>