testing_webpage/api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns = [
    url(r'^get[-_]public[-_]posts$', views.get_public_posts, name='get_public_posts'),
    url(r'^add[-_]messages$', views.add_messages, name='add_messages'),
    url(r'^save[-_]leads$', views.save_leads, name='save_leads'),
    url(r'^get[-_]leads[-_]to[-_]filter$', views.get_leads_to_filter, name='get_leads_to_filter'),
    url(r'^get[-_]domains[-_]to[-_]filter$', views.get_domains_to_filter, name='get_domains_to_filter'),

    # API v1
    url(r'^v1/register$', views.register, name='register'),
    url(r'^v1/get[-_]work[-_]areas', views.get_work_areas, name='get_work_areas'),
    url(r'^v1/get[-_]cities$', views.get_cities, name='get_cities'),
    url(r'^v1/get[-_]campaigns$', views.get_campaigns, name='get_campaigns'),
]

testing_webpage/beta_invite/urls.py
from django.conf.urls import url

from . import views

app_name = 'beta_invite'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^registro$', views.register, name='register'),
    url(r'^pruebas$', views.tests, name='tests'),
    url(r'^test[-_]result$', views.get_test_result, name='test_result'),
    url(r'^add[-_]cv$', views.add_cv, name='add_cv'),
    url(r'^add[-_]cv[-_]changes$', views.add_cv_changes),
    url(r'^additional[-_]info$', views.additional_info, name='additional_info'),
    url(r'^save[-_]partial[-_]additional[-_]info$', views.save_partial_additional_info, name='save_partial_additional_info'),
    url(r'^active[-_]campaigns$', views.active_campaigns, name='active_campaigns'),
    url(r'^security[-_]politics$', views.security_politics, name='security_politics'),
    url(r'^apply$', views.apply, name='apply'),
    url(r'^home$', views.home, name='home'),
    url(r'^upload-audio-file$', views.upload_audio_file, name='upload-audio-file'),
]

testing_webpage/business/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from business import views

app_name = 'business'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # LOGIN AND LOGOUT
    url(r'^login$', auth_views.login, {'template_name': 'business/login.html', 'extra_context': {'error_message': ''}},
        name='login'),
    url(r'^logout$', auth_views.logout, {'next_page': 'business:index'}, name='logout'),
    # CREATE CAMPAIGN
    url(r'^seleccion-gratis$', views.start, name='start'),
    url(r'^seleccion[-_]gratis[-_]enviar$', views.start_post, name='start_post'),
    # CREATE CAMPAIGN WHEN USER IS LOGGED
    url(r'^crear[-_]enviar$', views.create_post, name='create_post'),
    # BUSINESS USER LOGGED
    url(r'^campañas/(?P<business_user_id>\d+)$', views.business_campaigns, name='business_campaigns'),
    url(r'^resumen/(?P<campaign_id>\d+)$', views.summary, name='summary'),
    url(r'^online-demo$', views.online_demo, name='online_demo'),
    url(r'^tablero-de-control/(?P<business_user_id>\d+)/(?P<campaign_id>\d+)/(?P<state_name>.*)/$', views.dashboard, name='dashboard'),
    url(r'^tablero-de-control/(?P<campaign_id>\d+)/request-candidates$', views.request_candidates, name='request_candidates'),
    url(r'^perfil-del-candidato/(?P<candidate_id>\d+)$', views.candidate_profile, name='candidate_profile'),
    # CONTACT
    url(r'^contactanos$', views.contact_form, name='contact_form'),
    url(r'^contact[-_]form[-_]post$', views.contact_form_post, name='contact_form_post'),
    # START
    url(r'^get-work-area-requirement/(?P<work_area_id>\d+)$', views.get_work_area_requirement, name='get_work_area_requirement'),
    # PAYU
    url(r'payment[-_]confirmation$', views.payment_confirmation, name='payment_confirmation'),
    # DEMO SCHEDULED
    url(r'^demo[-_]scheduled$', views.demo_scheduled, name='demo_scheduled'),
    # SAVE CANDIDATE COMMENTS
    url(r'^save[-_]comments$', views.save_comments, name='save_comments'),
    # CHANGE CANDIDATE STATE
    url(r'^change[-_]state$', views.change_state, name='change_state'),

    # TODO: This search url should be deleted?
    url(r'^search$', views.search, name='search'),
    url(r'^results$', views.calculate_result, name='results'),
    url(r'^business[-_]signup$', views.business_signup, name='business_signup'),
    url(r'^home$', views.home, name='home'),
    # TODO: Worst hack ever, replace for something like: \?id=[0-9]+
    url(r'^results/(?P<pk>\d+)$', views.render_result, name='render_result'),
]

'''
url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    auth_views.password_reset_confirm, name='password_reset_confirm'),
url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
'''

testing_webpage/dashboard/urls.py
from django.conf.urls import url

from . import views
from . import stats

app_name = 'dashboard'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # All tests
    url(r'^tests_list$', views.tests_list, name='tests_list'),

    # Campaign
    url(r'^campaign/(?P<campaign_id>\d+)$', views.edit_campaign_candidates, name='campaign'),
    url(r'^campaign/new$', views.new_campaign, name='new_campaign'),
    url(r'^campaign/create$', views.create_campaign, name='create_campaign'),
    url(r'^campaign/edit/(?P<campaign_id>\d+)$', views.edit_campaign, name='edit_campaign'),
    url(r'^campaign/update[-_]basic[-_]properties$', views.update_basic_properties),
    url(r'^campaign/delete/(?P<pk>\d+)$', views.delete_campaign, name='delete_campaign'),
    url(r'^campaign/candidate/(?P<candidate_id>\d+)$', views.candidate_detail, name='candidate_detail'),

    # Campaign tests
    url(r'^campaign/(?P<pk>\d+)/add[-_]test$', views.add_test),
    url(r'^campaign/(?P<pk>\d+)/delete[-_]test$', views.delete_test),
    url(r'^campaign/(?P<pk>\d+)/tests$', views.tests),

    # Test
    # url(r'^', include('home.urls', namespace='home')),
    url(r'^test/(?P<pk>\d+)$', views.edit_test, name='test_edit'),
    url(r'^test/new$', views.new_test, name='new_test'),
    url(r'^test/save$', views.save_test, name='save_test'),
    url(r'^test/update/(?P<pk>\d+)$', views.update_test, name='update_test'),
    url(r'^test/delete[-_]question$', views.delete_question, name='delete_question'),
    url(r'^test/delete[-_]answer$', views.delete_answer, name='delete_answer'),
    url(r'^test/duplicate/(?P<pk>\d+)$', views.duplicate_test, name='duplicate_test'),

    # Bullets
    url(r'^campaign/(?P<pk>\d+)/bullets$', views.bullets),
    url(r'^campaign/update[-_]bullets$', views.update_bullets),
    url(r'^campaign/delete[-_]bullet$', views.delete_bullet),

    # Interview
    url(r'^edit[-_]intro[-_]video$', views.edit_intro_video, name='edit_intro_video'),
    url(r'^campaign/interview/(?P<pk>\d+)$', views.interview, name='interview'),
    url(r'^campaign/check_interview$', views.check_interview, name='check_interview'),
    url(r'^campaign/interview/create[-_]interview[-_]question$', views.create_interview_question, name='create_interview_question'),
    url(r'^campaign/interview/update[-_]interview[-_]question$', views.update_interview_question, name='update_interview_question'),
    url(r'^campaign/interview/delete[-_]interview[-_]question$', views.delete_interview_question, name='delete_interview_question'),

    # Auto messenger
    url(r'^send[-_]new[-_]contacts$', views.send_new_contacts, name='send_new_contacts'),
    url(r'^send[-_]messages$', views.send_messages, name='send_messages'),

    # stats
    url(r'^candidates[-_]stats$', stats.candidate_count, name='candidates_stats'),
    url(r'^campaign[-_]stats$', stats.campaign_count, name='campaign_stats'),
    url(r'^number[-_]of[-_]forecasts$', stats.number_of_forecasts, name='number_of_forecasts'),
    url(r'^positive[-_]forecasts$', stats.positive_forecasts, name='positive_forecasts'),
    url(r'^negative[-_]forecasts$', stats.negative_forecasts, name='negative_forecasts'),
    url(r'^candidates[-_]per[-_]user$', stats.candidates_per_user, name='candidates_per_user'),
    url(r'^candidates[-_]from[-_]old[-_]users$', stats.candidates_from_old_users, name='candidates_from_old_users'),
    url(r'^stuck[-_]candidates$', stats.stuck_candidates, name='stuck_candidates'),
    url(r'^recommended[-_]candidates$', stats.recommended_candidates, name='recommended_candidates'),
    url(r'^paid-campaign-registrations$', stats.get_paid_campaign_registrations, name='paid_campaign_registrations'),
    url(r'^unique-users-registrations$', stats.get_unique_users_registrations, name='unique_users_registrations'),
]

testing_webpage/business/models.py
import json

from django.db import models
from django.contrib.auth.models import User as AuthUser
from django.contrib.postgres.fields import JSONField
from django.core.exceptions import ObjectDoesNotExist

import basic_common
from beta_invite.models import Country, Education, Profession, Campaign
from business.more_models import Company


class Plan(models.Model):

    name = models.CharField(max_length=200)
    name_es = models.CharField(max_length=200, null=True)
    message = models.CharField(max_length=200, null=True)
    message_es = models.CharField(max_length=200, null=True)
    explanation = models.CharField(max_length=10000, null=True)
    explanation_es = models.CharField(max_length=10000, null=True)
    time = models.IntegerField(default=10)  # number of days.
    candidates = models.IntegerField(default=10)  # candidates: selected applicants
    applicants = models.IntegerField(default=100)  # applicants: people that applied before any filter.
    interview_price = models.CharField(max_length=200, null=True)
    interview_price_es = models.CharField(max_length=200, null=True)
    contract_warranty = models.CharField(max_length=200, null=True)
    contract_warranty_es = models.CharField(max_length=200, null=True)

    def __str__(self):
        return '{0}'.format(self.name)

    # adds custom table name
    class Meta:
        db_table = 'plans'


class Industry(models.Model):

    name = models.CharField(max_length=200)

    # adds custom table name
    class Meta:
        db_table = 'industries'

    def __str__(self):
        return '{0}'.format(self.name)


class BusinessUser(models.Model):

    email = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    ip = models.GenericIPAddressField(null=True)
    plan = models.ForeignKey(Plan, null=True, on_delete=models.SET_NULL)
    phone = models.CharField(max_length=40, null=True)
    campaigns = models.ManyToManyField(Campaign)
    company = models.ForeignKey(Company, null=True, on_delete=models.SET_NULL)
    industry = models.ForeignKey(Industry, null=True, on_delete=models.SET_NULL)
    additional_email = models.CharField(max_length=200, null=True)
    # Foreign key to the auth_user table. So that this table can cleanly be in charge of authentication
    auth_user = models.ForeignKey(AuthUser, null=True, on_delete=models.SET_NULL)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{0}, {1}, {2}'.format(self.name, self.email, self.company)

    def change_to_international_phone_number(self, campaign, add_plus=False):
        calling_code = campaign.get_calling_code()
        self.phone = basic_common.change_to_international_phone_number(self.phone, calling_code, add_plus=add_plus)
        return self.phone

    @staticmethod
    def get_business_user(user):
        """
        Given a auth User it gets the business User
        :param user: Auth User
        :return: Business User or None
        """
        if user and user.id:
            try:
                return BusinessUser.objects.get(auth_user=user)
            except ObjectDoesNotExist:
                return None
        return None

    def is_peaku(self):
        return 'peaku' in self.email

    # adds custom table name
    class Meta:
        db_table = 'business_users'


class Visitor(models.Model):

    ip = models.GenericIPAddressField(null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{0}, {1}'.format(self.ip, self.created_at)


class Contact(models.Model):

    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=40, null=True)
    message = models.CharField(max_length=5000, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{0}, {1}, {2}, {3}'.format(self.name, self.email, self.phone, self.message)

    # adds custom table name
    class Meta:
        db_table = 'contacts'


class Search(models.Model):

    ip = models.GenericIPAddressField(null=True)
    country = models.ForeignKey(Country, null=True)
    profession = models.ForeignKey(Profession, null=True)
    education = models.ForeignKey(Education, null=True)
    experience = models.IntegerField(null=True)
    text = models.CharField(max_length=10000, null=True)
    user_ids = JSONField(null=True)

    def set_user_ids(self, x):
        self.user_ids = json.dumps(x)

    def get_user_ids(self):
        return json.loads(self.user_ids)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'id: {0}, ip: {1}, user_ids: {2}'.format(self.pk, self.ip, self.user_ids)

    # adds custom table name
    class Meta:
        db_table = 'searches'

testing_webpage/business/templates/business/dashboard/business_campaigns.html
{% extends 'white_header_base.html'%}
{% load static %}
{% load i18n %}
{% load app_filters %}
{% load compress %}
{% block title %}Selección, contratación y reclutamiento de personal{% endblock %}
{% block extra_meta %}
    <meta name="description"  content="Publica y comparte ofertas laborales, realiza pruebas relacionadas al cargo y selecciona al mejor personal. Podrás buscar, filtrar y comunícarte fácilmente con los candidatos en todas las etapas del proceso." />
    <meta name="keywords" content="cazatalentos, selección de personal, reclutamiento personal, contratacion personal, selección personal, agencias, reclutamiento, reclutamiento empleados, busqueda personal, preselección personal, headhunter, agencia empleo" />
{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'business/css/business_campaigns.css' %}">
{% endblock %}

{% block content %}
    <form class="content" action="{% url 'business:start' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="business_user_id" value="{{ business_user_id }}" />
    </form>
    <h1 style="text-align:center; margin:50px 0px">{% trans "Campaigns" %}</h1>
        <div style="min-height: 500px;">
        {% for campaign in campaigns %}
            <div class="campaign-div">
                <div class="row">
                    <p class="tittle">{{ campaign.title_es }}</p>
                    <div class="col-lg-12">
                        <a href="{{ campaign|get_campaign_url }}" class="cta" target="_blank"><b>Ver la oferta que ven los candidatos</b></a>
                    <br>
                    <br>
                        {% show_candidates campaign user as show_the_candidates %}
                        {% if show_the_candidates %}
                            <a class="cta" href="{% url 'business:dashboard' business_user_id=business_user_id campaign_id=campaign.id state_name='recommended' %}" target="_blank"><b>VER CANDIDATOS</b></a>
                        {% else %}
                            <a class="cta" style="color:grey" title="Activa premium para ver candidatos"><b>VER CANDIDATOS</b></a>
                        {% endif %}
                    <br>
                    <br>
                    <p><b>EMPRESA:</b> {{ campaign|get_business_user_company_with_campaign }}</p>
                    <p><b>REPRESENTANTE:</b> {{ campaign|get_business_user_name_with_campaign }}</p>
                    <p><b>ESTADO:</b> {{ campaign.state.name_es }}</p>
                    <p><b>FECHA DE CREACIÓN:</b> {{ campaign.local_date }}</p>
                    {% if campaign.salary_low_range >= 0 %}
                        <p><b>SALARIO:</b> ${{ campaign.salary_low_range }} a ${{ campaign.salary_high_range }} </p>
                    {% endif %}
                    {% if campaign.free_trial == True and campaign.state.name_es != 'Activa' and campaign.base != 0 %}
                        {% if campaign.salary_low_range >= 0 and campaign.work_area.pk not in invalid_work_areas %}
                            <form method="post" action="{{ action_url }}" accept-charset="UTF-8">
                                <!--PAYMENT GENERIC INFO-->
                                <input name="ApiKey" type="hidden" value="{{ apikey }}"/>
                                <input name="merchantId" type="hidden" value="{{ merchant_id }}"/>
                                <input name="accountId" type="hidden" value="{{ account_id }}"/>
                                <input name="currency" type="hidden" value="{{ currency }}"/>
                                <input name="test" type="hidden" value="{{ test }}"/>
                                <input name="description" type="hidden" value="{{ description }}"/>
                                <!--PAYMENT DYNAMIC INFO-->
                                <input name="buyerFullName" type="hidden" value="{{ buyer_name }}"/>
                                <input name="buyerEmail" type="hidden" value="{{ buyer_email }}"/>
                                <input name="referenceCode" type="hidden" value="{{ campaign.reference_code }}"/>
                                <input name="amount" type="hidden" value="{{ campaign.amount }}"/>
                                <input name="tax" type="hidden" value="{{ campaign.tax }}"/>
                                <input name="taxReturnBase" type="hidden" value="{{ campaign.base }}"/>
                                <input name="signature"  type="hidden" value="{{ campaign.signature }}"/>
                                <!--RESPONSE URL VISIBLE-->
                                <input name="responseUrl" type="hidden"  value="{{ response_url }}{{ campaign.pk }}" >
                                <!--CONFIRMATION URL NOT VISIBLE-->
                                <input name="confirmationUrl" type="hidden"  value="{{ confirmation_url }}" >
                                <!--EXTRA INFO-->
                                <input name="extra1" type="hidden"  value="{{ campaign.pk }}" >
                                <input type="submit" class="submit-button-strong" value="Activar Premium"/>
                            </form>
                        {% else %}
                            <p>Para activar esta campaña debe comunicarse con nosotros</p>
                        {% endif %}
                    {% endif %}
                </div>
                </div>
            </div>
        {% endfor %}
        </div>
{% endblock %}

testing_webpage/business/templates/business/dashboard/candidates.html
{% load static %}
{% load app_filters %}
{% load i18n %}

{% for candidate in candidates_list %}
    <div class="candidate-div">
        {% include "business/dashboard/candidate_for_campaign.html" with candidate=candidate business_state=business_state %}
    </div>
{% endfor %}

testing_webpage/business/templates/business/dashboard/dashboard.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% load app_filters %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <title>PeakU - Tablero de control</title>
        <!--Latest compiled and minified bootstrap CSS-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <!--Our Css-->
        <link rel="stylesheet" type="text/css" href="{% static 'business/css/dashboard.css' %}">
        <!-- Latest jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <!-- Latest compiled Bootstrap JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <!--Our JS-->
        <script src="{% static 'business/js/dashboard.js' %}"></script>
        <script>
            function openContent(evt, state) {
                var i, tabcontent, tablinks;
                tabcontent = document.getElementsByClassName("tabcontent");
                for (i = 0; i < tabcontent.length; i++) {
                    tabcontent[i].style.display = "none";
                }
                tablinks = document.getElementsByClassName("tablinks");
                for (i = 0; i < tablinks.length; i++) {
                    tablinks[i].className = tablinks[i].className.replace(" active", "");
                }
                $("." + state).css("display", "block");
                evt.currentTarget.className += " active";

                if ($(window).width() > 768) {
                    $(".tablinks").css("width", "100%");
                    $(".tablinks").css("margin-left", "0%");
                    evt.currentTarget.style.width = "115%";
                    evt.currentTarget.style.marginLeft = "-15%";
                }
            }
        </script>
    </head>
    <body>
        <div class="topnav" id="myTopnav">
            <a href="/staffing" class="logo"><img src="{% static 'business/img/logo-color-negro.png' %}"></a>
            <a href="{% url 'business:logout' %}">{% trans "LOG OUT" %}</a>
            <a class="navButton" style="font-size: 15px;width:170px;color: white;border-radius:40px;margin-top: 30px;padding:5px 16px;background:#F47B20;"
                role="button" href="{% url 'business:start' %}">+  CREAR OFERTA</a>
            <a href="{% url 'business:business_campaigns' business_user_id=business_user.pk %}">Mis ofertas</a>
            <a href="{% url 'business:summary' campaign_id=campaign.pk %}">VER RESUMEN DE LA OFERTA</a>
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
            <i class="fa fa-bars"></i>
            </a>
        </div>
        <div id="contact-buttons">
            <a href="https://api.whatsapp.com/send?phone=573174236989" target="_blank"><img src="{% static 'business/img/boton-whatsapp.png' %}" width="100px" id="whatsapp-pc"></a>
        </div>
        <div class="background" id="background">
            <div class="gradient1">
                <div class="row one"></div>
                <div class="row two">
                    <div class="col-lg-12 campaign bold">{{ campaign.title_es }}</div>
                </div>
                <div class="row plan-type"></div>
                <div class="row three">
                    <div class="col-lg-3 col-xs-12"></div>
                    <div class="col-lg-9 col-xs-12 gradient2">
                        <p class="date regular">FECHA DE PUBLICACIÓN: {{ campaign.created_at }}</p>
                        <br>
                        {% if campaign.state.name == 'Active' %}
                            <p class="status bold">ESTADO: activa</p>
                        {% elif campaign.state.name == 'Inactive' %}
                            <p class="status bold">ESTADO: inactiva</p>
                        {% else %}
                            <p class="status bold">ESTADO: terminada</p>
                        {% endif%}
                        <br>
                        {% if campaign.free_trial == True %}
                            <p class="status bold">(Prueba gratis)</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="tab-div col-lg-2 col-md-2 col-sm-2 col-xs-12 no-padding">
                <div class="tab" id="tab">
                    <button class="tablinks" onclick="openContent(event, 'recommended-profiles')" id="active-recommended"><span class="tab-button-span">{{ num_recommended }}</span>{% trans 'Selected' %}</button>
                    <button class="tablinks" onclick="openContent(event, 'relevant-profiles')" id="active-relevant"><span class="tab-button-span">{{ num_relevant }}</span>{% trans 'Pre-selected' %}</button>
                    <button class="tablinks" onclick="openContent(event, 'applicants-profiles')" id="active-applicants"><span class="tab-button-span">{{ num_applicants }}</span>{% trans 'Prospects' %}</button>
                </div>
            </div>
            <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 no-padding">
                <div class="row big-div">
                    <div class="tabcontent recommended-profiles">
                        {% include "business/dashboard/dashboard_column.html" with candidates_list=recommended business_state='recommended' campaign_evaluation=recommended_evaluation %}
                    </div>
                    <div class="tabcontent relevant-profiles">
                        {% include "business/dashboard/dashboard_column.html" with candidates_list=relevant business_state='relevant' campaign_evaluation=relevant_evaluation %}
                    </div>
                    <div class="tabcontent applicants-profiles">
                        {% include "business/dashboard/dashboard_column.html" with candidates_list=applicants business_state='applicants' campaign_evaluation=applicant_evaluation %}
                    </div>
                </div>
            </div>
        </div>
        <!----------------------------------------------FOOTER--------------------------------------------------------->
        <footer class="container-fluid">
            <div class="row footer-navigation">
                <div class="col-md-2 col-md-2"></div>
                <div class="col-md-3 col-md-3 navfooter">
                    <ul>
                        <li><a href="#">Nosotros</a></li>
                        <li><a href="{% url 'business:contact_form' %}">Contáctanos</a></li>
                        <li><a href="{% url 'beta_invite:index' %}">Personas</a></li>
                    </ul>
                </div>
                <div class="col-md-2 col-md-2 social">
                    <a href="https://www.linkedin.com/company-beta/16241506/" target="_blank"><img src="{% static 'business/img/linkedin.png' %}"></a>
                    <a href="https://www.facebook.com/PeakU-Latam-1916685895214519/?ref=aymt_homepage_panel" target="_blank">
                    <img src="{% static 'business/img/facebook.png' %}"></a>
                    <a href="#" target="_blank"><img src="{% static 'business/img/instagram.png' %}"></a>
                    <a href="#" target="_blank"><img src="{% static 'business/img/twitter.png' %}"></a>
                </div>
                <div class=" col-md-1 col-md-1"></div>
                <div class=" col-md-2 col-md-2 navfootercontact">
                    <div class="logo-white"><a href="#"><img src="{% static 'business/img/logo-white.png' %}"></a></div>
                    contacto@peaku.co<br>
                    +57 317 4236989<br>
                    Colombia
                </div>
            </div>
            <div class=" col-md-2 col-md-2 "></div>
            </div>
            <div class="row">
                <div class="col-1 col-md-1"></div>
                <div class="col-10 copyright">Copyright 2018 © PeakU. Todos los derechos reservados.</div>
                <div class="col-1"></div>
            </div>
        </footer>
        <script>
            function myFunction() {
                var x = document.getElementById("myTopnav");
                if (x.className === "topnav") {
                    x.className += " responsive";
                } else {
                    x.className = "topnav";
                }
            }
        </script>
        <script>
            $(document).ready(function() {
                set_background("{{ campaign.image }}", "background");

                if ($(window).width() > 768) {
                    $.stickysidebarscroll("#tab",{offset: {top: 0, bottom: 250}});
                }
                document.getElementById("active-"+"{{ business_state.name }}").click();
            });
        </script>
        <script>
            $( window ).resize(function() {
                set_background("{{ campaign.image }}", "background");
            });
        </script>
        <script>
            // Adds candidates as it scrolls down...
            $(window).scroll(function() {
               if($(window).scrollTop() + $(window).height() > $(document).height() - 2000) {
                   recommended = $('.recommended-profiles');
                   relevant = $('.relevant-profiles');
                   prospect = $('.applicants-profiles');

                   if (recommended.css('display') == 'block') {
                        request_candidates('recommended', {{ campaign.pk }});
                   }else if (relevant.css('display') == 'block') {
                        request_candidates('relevant', {{ campaign.pk }});
                   }else if (prospect.css('display') == 'block') {
                        request_candidates('applicants', {{ campaign.pk }});
                   }
               }
            });
        </script>
    </body>
</html>