testing_webpage/api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns = [
    url(r'^get[-_]public[-_]posts$', views.get_public_posts, name='get_public_posts'),
    url(r'^add[-_]messages$', views.add_messages, name='add_messages'),
    url(r'^save[-_]leads$', views.save_leads, name='save_leads'),
    url(r'^get[-_]leads[-_]to[-_]filter$', views.get_leads_to_filter, name='get_leads_to_filter'),
    url(r'^get[-_]domains[-_]to[-_]filter$', views.get_domains_to_filter, name='get_domains_to_filter'),

    # API v1
    url(r'^v1/register$', views.register, name='register'),
    url(r'^v1/get[-_]work[-_]areas', views.get_work_areas, name='get_work_areas'),
    url(r'^v1/get[-_]cities$', views.get_cities, name='get_cities'),
    url(r'^v1/get[-_]campaigns$', views.get_campaigns, name='get_campaigns'),
]

testing_webpage/business/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from business import views

app_name = 'business'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # LOGIN AND LOGOUT
    url(r'^login$', auth_views.login, {'template_name': 'business/login.html', 'extra_context': {'error_message': ''}},
        name='login'),
    url(r'^logout$', auth_views.logout, {'next_page': 'business:index'}, name='logout'),
    # CREATE CAMPAIGN
    url(r'^seleccion-gratis$', views.start, name='start'),
    url(r'^seleccion[-_]gratis[-_]enviar$', views.start_post, name='start_post'),
    # CREATE CAMPAIGN WHEN USER IS LOGGED
    url(r'^crear[-_]enviar$', views.create_post, name='create_post'),
    # BUSINESS USER LOGGED
    url(r'^campañas/(?P<business_user_id>\d+)$', views.business_campaigns, name='business_campaigns'),
    url(r'^resumen/(?P<campaign_id>\d+)$', views.summary, name='summary'),
    url(r'^online-demo$', views.online_demo, name='online_demo'),
    url(r'^tablero-de-control/(?P<business_user_id>\d+)/(?P<campaign_id>\d+)/(?P<state_name>.*)/$', views.dashboard, name='dashboard'),
    url(r'^tablero-de-control/(?P<campaign_id>\d+)/request-candidates$', views.request_candidates, name='request_candidates'),
    url(r'^perfil-del-candidato/(?P<candidate_id>\d+)$', views.candidate_profile, name='candidate_profile'),
    # CONTACT
    url(r'^contactanos$', views.contact_form, name='contact_form'),
    url(r'^contact[-_]form[-_]post$', views.contact_form_post, name='contact_form_post'),
    # START
    url(r'^get-work-area-requirement/(?P<work_area_id>\d+)$', views.get_work_area_requirement, name='get_work_area_requirement'),
    # PAYU
    url(r'payment[-_]confirmation$', views.payment_confirmation, name='payment_confirmation'),
    # DEMO SCHEDULED
    url(r'^demo[-_]scheduled$', views.demo_scheduled, name='demo_scheduled'),
    # SAVE CANDIDATE COMMENTS
    url(r'^save[-_]comments$', views.save_comments, name='save_comments'),
    # CHANGE CANDIDATE STATE
    url(r'^change[-_]state$', views.change_state, name='change_state'),

    # TODO: This search url should be deleted?
    url(r'^search$', views.search, name='search'),
    url(r'^results$', views.calculate_result, name='results'),
    url(r'^business[-_]signup$', views.business_signup, name='business_signup'),
    url(r'^home$', views.home, name='home'),
    # TODO: Worst hack ever, replace for something like: \?id=[0-9]+
    url(r'^results/(?P<pk>\d+)$', views.render_result, name='render_result'),
]

'''
url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    auth_views.password_reset_confirm, name='password_reset_confirm'),
url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
'''

testing_webpage/dashboard/urls.py
from django.conf.urls import url

from . import views
from . import stats

app_name = 'dashboard'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # All tests
    url(r'^tests_list$', views.tests_list, name='tests_list'),

    # Campaign
    url(r'^campaign/(?P<campaign_id>\d+)$', views.edit_campaign_candidates, name='campaign'),
    url(r'^campaign/new$', views.new_campaign, name='new_campaign'),
    url(r'^campaign/create$', views.create_campaign, name='create_campaign'),
    url(r'^campaign/edit/(?P<campaign_id>\d+)$', views.edit_campaign, name='edit_campaign'),
    url(r'^campaign/update[-_]basic[-_]properties$', views.update_basic_properties),
    url(r'^campaign/delete/(?P<pk>\d+)$', views.delete_campaign, name='delete_campaign'),
    url(r'^campaign/candidate/(?P<candidate_id>\d+)$', views.candidate_detail, name='candidate_detail'),

    # Campaign tests
    url(r'^campaign/(?P<pk>\d+)/add[-_]test$', views.add_test),
    url(r'^campaign/(?P<pk>\d+)/delete[-_]test$', views.delete_test),
    url(r'^campaign/(?P<pk>\d+)/tests$', views.tests),

    # Test
    # url(r'^', include('home.urls', namespace='home')),
    url(r'^test/(?P<pk>\d+)$', views.edit_test, name='test_edit'),
    url(r'^test/new$', views.new_test, name='new_test'),
    url(r'^test/save$', views.save_test, name='save_test'),
    url(r'^test/update/(?P<pk>\d+)$', views.update_test, name='update_test'),
    url(r'^test/delete[-_]question$', views.delete_question, name='delete_question'),
    url(r'^test/delete[-_]answer$', views.delete_answer, name='delete_answer'),
    url(r'^test/duplicate/(?P<pk>\d+)$', views.duplicate_test, name='duplicate_test'),

    # Bullets
    url(r'^campaign/(?P<pk>\d+)/bullets$', views.bullets),
    url(r'^campaign/update[-_]bullets$', views.update_bullets),
    url(r'^campaign/delete[-_]bullet$', views.delete_bullet),

    # Interview
    url(r'^edit[-_]intro[-_]video$', views.edit_intro_video, name='edit_intro_video'),
    url(r'^campaign/interview/(?P<pk>\d+)$', views.interview, name='interview'),
    url(r'^campaign/check_interview$', views.check_interview, name='check_interview'),
    url(r'^campaign/interview/create[-_]interview[-_]question$', views.create_interview_question, name='create_interview_question'),
    url(r'^campaign/interview/update[-_]interview[-_]question$', views.update_interview_question, name='update_interview_question'),
    url(r'^campaign/interview/delete[-_]interview[-_]question$', views.delete_interview_question, name='delete_interview_question'),

    # Auto messenger
    url(r'^send[-_]new[-_]contacts$', views.send_new_contacts, name='send_new_contacts'),
    url(r'^send[-_]messages$', views.send_messages, name='send_messages'),

    # stats
    url(r'^candidates[-_]stats$', stats.candidate_count, name='candidates_stats'),
    url(r'^campaign[-_]stats$', stats.campaign_count, name='campaign_stats'),
    url(r'^number[-_]of[-_]forecasts$', stats.number_of_forecasts, name='number_of_forecasts'),
    url(r'^positive[-_]forecasts$', stats.positive_forecasts, name='positive_forecasts'),
    url(r'^negative[-_]forecasts$', stats.negative_forecasts, name='negative_forecasts'),
    url(r'^candidates[-_]per[-_]user$', stats.candidates_per_user, name='candidates_per_user'),
    url(r'^candidates[-_]from[-_]old[-_]users$', stats.candidates_from_old_users, name='candidates_from_old_users'),
    url(r'^stuck[-_]candidates$', stats.stuck_candidates, name='stuck_candidates'),
    url(r'^recommended[-_]candidates$', stats.recommended_candidates, name='recommended_candidates'),
    url(r'^paid-campaign-registrations$', stats.get_paid_campaign_registrations, name='paid_campaign_registrations'),
    url(r'^unique-users-registrations$', stats.get_unique_users_registrations, name='unique_users_registrations'),
]

testing_webpage/business/views.py
import os
import json
from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'testing_webpage.testing_webpage.settings')
application = get_wsgi_application()

import smtplib
import hashlib
from datetime import datetime
from django.contrib.auth.decorators import login_required
from ipware.ip import get_ip
from django.shortcuts import render, redirect
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import login, authenticate
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.forms import AuthenticationForm
from django.utils import formats
from django.http import HttpResponseBadRequest, HttpResponse, JsonResponse
from decouple import config
from django.db import models
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import get_template

import common
import business
import beta_invite

from beta_invite.util import messenger
from business import search_module, prospect_module
from beta_invite.util import email_sender
from business import constants as cts
from beta_invite.models import User, WorkArea, EmailType, Campaign, Test, Price, CampaignState
from business.models import Plan, Contact, Search, BusinessUser, Company
from beta_invite.models import Requirement
from business.custom_user_creation_form import CustomUserCreationForm
from dashboard import campaign_module
from dashboard.models import Candidate, BusinessState, Comment
from business import dashboard_module
from testing_webpage.models import BusinessUserPendingEmail, CampaignPendingEmail


TAX = 0.19
DEFAULT_BASE_PRICE = 0
INVALID_WORK_AREAS = [8, 14, 17]
MAX_CANDIDATES_LOAD = 20


def index(request):
    """
    will render and have the same view as /beta_invite except for message customization.
    Args:
        request: Object
    Returns: Save
    """

    ip = get_ip(request)

    business.models.Visitor(ip=ip).save()
    return render(request, cts.INDEX_VIEW_PATH, {'error_message': ''})


def search(request):
    """
    will render the search view.
    Args:
        request: Object
    Returns: Save
    """

    ip = get_ip(request)
    action_url = '/business/results'
    countries, cities, education, professions = beta_invite.views.get_drop_down_values(request.LANGUAGE_CODE)

    business.models.Visitor(ip=ip).save()
    return render(request, cts.SEARCH_VIEW_PATH, {'main_message': _("Discover amazing people"),
                                                  'secondary_message': _("We search millions of profiles and find the ones that best suit your business"),
                                                  'action_url': action_url,
                                                  'countries': countries,
                                                  'education': education,
                                                  'professions': professions,
                                                  })


def calculate_result(request):
    """
    Args:
        request: Request object
    Returns: renders results.html view.
    """

    user_ids = search_module.get_common_search_info(request)

    search_obj = Search(ip=get_ip(request),
                        country=None,
                        education=None,
                        profession=None,
                        experience=None,
                        text=search_module.get_text_from_request(request),
                        user_ids=user_ids, )

    search_obj.save()

    return redirect('results/{id}'.format(id=search_obj.id))


def render_result(request, pk):
    """
    Gets a stored search back to life.
    Args:
        request: HTTP request.
        pk: primary key of a search
    Returns: Renders search results.
    """

    search_obj = Search.objects.get(pk=pk)
    users = [User.objects.get(pk=u_id) for u_id in search_obj.user_ids]
    params = {'main_message': _("Discover amazing people"),
              'secondary_message': _("We search millions of profiles and find the ones that best suit your business"),
              'users': users}

    return render(request, cts.RESULTS_VIEW_PATH, params)


def translate_message(plan, language_code):
    """
    Args:
        plan: Object of class Plan.
        language_code:
    Returns:
    """
    if 'es' in language_code:
        plan.message = plan.message_es

    return plan


def get_plan(request):
    """
    Args:
        request: HTTP request
    Returns: Returns a Plan obj
    """

    plan_id = request.POST.get('plan_id')
    try:
        plan = Plan.objects.get(pk=plan_id)
    except ObjectDoesNotExist:
        # Gets the default plan.
        plan = Plan.objects.get(pk=4)

    return translate_message(plan, request.LANGUAGE_CODE)


def send_signup_emails(business_user, language_code, campaign):

    if campaign is None:
        body_filename = 'business_signup_notification_email_body'
        body_input = 'business_signup_email_body'
        BusinessUserPendingEmail.add_to_queue(the_objects=business_user,
                                              language_code=language_code,
                                              body_input=body_input,
                                              subject=_('Welcome to PeakU'),
                                              email_type=EmailType.objects.get(name='business_welcome'))
    else:
        body_filename = 'business_start_signup_notification_email_body'
        body_input = 'business_start_signup_email_body'
        messenger.send(objects=campaign,
                       language_code=language_code,
                       body_input=body_input)
        CampaignPendingEmail.add_to_queue(the_objects=campaign,
                                          language_code=language_code,
                                          body_input=body_input,
                                          subject='Oferta publicada exitosamente - {campaign}',
                                          email_type=EmailType.objects.get(name='business_welcome'))

    email_sender.send_internal(contact=business_user,
                               language_code=language_code,
                               body_filename=body_filename,
                               subject='Business User acaba de registrarse!!!',
                               campaign=campaign)


def first_sign_in(signup_form, request):
    """
    This method is used to do stuff after validating signup-data. Also logs in.
    Args:
        signup_form: Form obj
        request: HTTP obj
    Returns: None, first auth and sign-in, saves objects
    """

    signup_form.save()
    username = signup_form.cleaned_data.get('username')
    password = signup_form.cleaned_data.get('password1')

    # Creates a Authentication user
    auth_user = authenticate(username=username,
                             password=password)

    company = Company(name=request.POST.get('company'))
    company.save()

    # New BusinessUser pointing to the AuthUser
    business_user = business.models.BusinessUser(name=request.POST.get('name'),
                                                 company=company,
                                                 email=request.POST.get('username'),
                                                 phone=request.POST.get('phone'),
                                                 ip=get_ip(request),
                                                 plan=get_plan(request),
                                                 auth_user=auth_user)

    business_user.save()

    login(request, auth_user)

    return business_user


def get_business_user(request):
    """
    Given a request that has the AuthUser.id will get the BusinessUser
    Args:
        request: HTTP request object.
    Returns: A BusinessUser object.
    """
    return BusinessUser.objects.get(auth_user_id=request.user.id)


def get_first_error_message(form):
    """
    :param form: AuthenticationForm or UserCreationForm
    :return: str with first error_message
    """
    error_messages = [m[0] for m in form.errors.values()]
    if len(error_messages) > 0:  # Takes first element from the errors dictionary
        error_message = error_messages[0]
    else:
        error_message = 'unknown error'
    return error_message


def simple_login_and_business_user(login_form, request):
    """
    :param login_form: a AuthenticationForm object
    :param request: HTTP
    :return: BusinessUser obj
    """
    username = login_form.cleaned_data.get('username')
    password = login_form.cleaned_data.get('password')

    # Creates a Authentication user
    auth_user = authenticate(username=username,
                             password=password)

    login(request, auth_user)

    return BusinessUser.objects.get(auth_user=auth_user)


def home(request):
    """
    Leads to Dashboard view.
    Args:
        request: HTTP request.
    Returns: displays all offers of a business
    """

    login_form = AuthenticationForm(data=request.POST)

    # TODO: generalize to set of blocked emails.
    if login_form.is_valid():

        business_user = simple_login_and_business_user(login_form, request)
        if request.POST.get('username') == 'admin@peaku.co':
            return redirect(common.get_host()+'/dashboard')
        else:
            return redirect('campañas/{}'.format(business_user.pk))

    else:
        error_message = get_first_error_message(login_form)
        return render(request, cts.BUSINESS_LOGIN, {'error_message': error_message})


def send_contact_emails(contact, language_code):

    try:
        email_sender.send(objects=contact,
                          language_code=language_code,
                          body_input='business_contact_email_body',
                          subject=_('Welcome to PeakU'))
        email_sender.send_internal(contact=contact,
                                   language_code=language_code,

testing_webpage/business/templates/business/business_signup.html
{% extends 'base.html'%}
{% load static %}   <!-- Generates the absolute URL of static files-->
{% load i18n %}     <!--Django translation-->

{% block title %}{% trans "Personnel Selection - PeakU" %}{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'business/css/start.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'business/css/signup.css' %}">
{% endblock %}

{% block content %}

<section class="section-container">

    <div class="row"> <!-- bootstrap row class -->
        <div class="col-sm-6">
            <img class="people-talking" src="{% static 'business/img/people_talking.jpg' %}"
            srcset="{% static 'business/img/people_talking.jpg' %} 2x,
            {% static 'business/img/people_talking.jpg' %} 3x">
        </div>

        <div class="col-sm-6">
            <!-- tag to scroll down to the contact form with url -->
            <a name="contactForm"></a>

            <h3 class="secondary-title" >{% trans "Sign Up" %}</h3>
            <div class="secondary-yellow-bar"></div>
            <br>
            <form class="my-form" enctype="multipart/form-data" method="post">

                {% csrf_token %}

                <input class="form-text" type="text" name="name"
                  placeholder="{% trans 'Your Full Name' %}" required="required" pattern="[A-Za-z\sáéíóúÑñÜüÁÉÍÓÚ]{1,200}">

                <input class="form-text" type="email" name="username"
                  placeholder="{% trans 'Your email' %}" required="required">

                <input class="form-text" type="tel" name="phone"
                  placeholder="{% trans 'Your phone' %}" required="required" pattern="[0-9\(\)\+\-\s\.extension]{7,40}">

                <input class="form-text" type="password" name="password1"
                  placeholder="{% trans 'Enter a password' %}" required="required">

                <input class="form-text" type="password" name="password2"
                  placeholder="{% trans 'Confirm password' %}" required="required">

                <input class="form-submit" type="submit" value="{% trans 'Sure!' %}">
            </form>
        </div>
    </div>
</section>


{% endblock %}

testing_webpage/business/templates/business/contact.html
{% extends 'white_header_base.html'%}
{% load static %}
{% load i18n %}
{% load app_filters %}
{% load compress %}
{% block extra_meta %}
<meta name="description" content="Resolvemos tus preguntas sobre nuestras ofertas de empleo y el procesos de selección y reclutamiento de personal para empresas en Colombia, Chile, Ecuador, Perú y Argentina." />
<meta name="keywords" content="cazatalentos, selección de personal, reclutamiento personal, contratacion personal, selección personal, agencias, reclutamiento, servicio de empleo , empleo, ofertas de empleo , headhunter, agencia empleo" />
{% endblock %}
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'business/css/contact_form.css' %}">
{% endblock %}
{% block content %}
<section class="section-container">
    <div class="row">
        <div class="col-lg-12">
            <div class="only-register-form">
                <div class="title">
                    <br>
                    <h2 style="font-size:35px; margin-top:10px; color:white; ">{{ main_message }}</h2>
					<b style="font-weight:500; color:white; text-transform: uppercase;">{% trans "Thanks for reaching out!" %}</b>
					<br>
					<b style="font-weight:400; color:white; font-size:18px">{% trans "We will contact you soon" %}</b>
					<br>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

testing_webpage/business/templates/business/contact_form.html
{% extends 'white_header_base.html'%}
{% load static %}
{% load i18n %}
{% load app_filters %}
{% load compress %}
{% block extra_meta %}
    <meta name="description" content="Resolvemos tus preguntas sobre nuestras ofertas de empleo y el procesos de selección y reclutamiento de personal para empresas en Colombia, Chile, Ecuador, Perú y Argentina." />
    <meta name="keywords" content="cazatalentos, selección de personal, reclutamiento personal, contratacion personal, selección personal, agencias, reclutamiento, servicio de empleo , empleo, ofertas de empleo , headhunter, agencia empleo" />
{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'business/css/contact_form.css' %}">
{% endblock %}
{% block content %}
    <section class="section-container">
        <div class="row">
            <div class="col-lg-12">
                <form class="only-register-form" action="{% url 'business:contact_form_post' %}" method="post">
                    {% csrf_token %}

                    <input class="form-text" type="text" name="name"
				        placeholder="{% trans 'Your Full Name' %}" required="required" pattern="[A-Za-z\sÁÉÍÓÚáéíóúÑñÜü]{1,200}">

                    <input class="form-text" type="email" name="email"
                         placeholder="{% trans 'Your email' %}" required="required">

                    <input class="form-text" type="tel" name="phone"
                         placeholder="{% trans 'Your phone (optional)' %}">

                    <textarea class="form-text-area" name="message" rows="10" cols="20" autocomplete="off" maxlength="500" placeholder="{% trans 'Add a message (optional)' %}"></textarea>

                    <input class="form-submit" type="submit" value="{% trans 'Sure!' %}">
                </form>
            </div>
        </div>
    </section>
{% endblock %}

testing_webpage/business/templates/business/login.html
{% extends 'base.html'%}
{% load static %}
{% load i18n %}
{% block title %}PeakU - Login{% endblock %}
{% block content %}
<div class="welcome-section" id="top" style="margin-bottom:20px; min-height:500px;">
    <h1 align="center" style="color:var(--brochure-blue)">{% trans "Log in to our platform" %}</h1>
    <div class="container" style="margin-top:50px;">

            <form method="post" style="text-align:center; margin-top:0px;" action="{% url 'business:home' %}" enctype="multipart/form-data">

            <input type="hidden" name="next" value="{{ next }}" />
            {% csrf_token %}
            {% trans "Your email" as email_placeholder %}
            <input style="font-family:Raleway; padding-left: 15px; font-size: 14px; height: 40px; margin-top:15px;
                border:solid 2px var(--brochure-blue); background-color:white; width: 250px;" id="username" type="email" name="username"
                placeholder="{{ email_placeholder }}" required="required">
            <br>
            {% trans "Enter your password" as password1_placeholder %}
            <input style="font-family:Raleway; padding-left: 15px; font-size: 14px; height: 40px; margin-top:15px;
                border:solid 2px var(--brochure-blue); background-color:white; width: 250px;" id="password" type="password" name="password"
                placeholder="{{ password1_placeholder }}" required="required">
            <br>
            {% trans "Log In" as submit_value %}
            <input style="height: 44px; border:  2px black; background:var(--brochure-blue); color:white; text-align:center;
                width: 81px; font-size: 16px; width: 255px; margin-bottom:20px; margin-top:15px; cursor:pointer;" type="submit" value="{{ submit_value }}">
            <br>
            <!--<a style="text-align:center" href="{% url 'password_reset' %}">¿Olvidaste la contraseña?</a>-->
            <br>
            <br>
        </form>
    </div>
</div>
<!-- any incoming error_message will print as an alert.-->
<script>
    {% if error_message %}
        alert("{{ error_message }}");
    {% endif %}
</script>
{% endblock %}

testing_webpage/business/templates/business/login_buttons.html
{% load i18n %}
{% load app_filters %}

{% if user|business_user_is_authenticated %}

    {% trans "Log Out" as logout_value %}
    <div align="right" style="margin-top:15px; margin-right:15px; cursor:pointer;">
        <form style="cursor:pointer;" action="{% url 'business:logout' %}">
            <input style="height: 34px; border: solid 0px white; background:#F8E676; color:black; text-align:center;
                   font-size: 16px; width: 110px; cursor:pointer;" type="submit" value="{{ logout_value }}">
        </form>
    </div>

{% else %}

    <div style="margin-top:15px; margin-right:15px; cursor:pointer;">

        {% trans "Log In" as login_value %}
        <form style="text-align: right; cursor:pointer;" action="{% url 'business:login' %}">
            <input style="height: 34px; border: solid 0px white; background:rgba(255, 255, 255, .0); color:#F8E676; text-align:center;
                   font-size: 16px; width: 110px; cursor:pointer;" type="submit" value="{{ login_value }}">
        </form>

    </div>
{% endif %}

testing_webpage/business/templates/business/signup.html
{% extends 'base.html'%}
{% load i18n %}
{% load static %}


{% block title %}{%  trans "PeakU - Employment Agency" %}{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'business/css/business_signup.css' %}">
{% endblock %}


{% block content %}
    <div id="background-white-rectangle">
        <h1 class="main-title">Regístrate</h1>
        <h2 id="description">{% trans "We connect people with companies, quickly and easily" %}</h2>

        <div id="who-am-i-div">
            <a href="{% url 'beta_invite:long_form' %}">
                <div id="user">
                    <img class="avatar-img" src="{% static 'beta_invite/img/user.png' %}">
                    <form id="person-form">
                        {% trans "Person" as person %}
                        <input id="person-input" type="button" value="{{ person }}">
                    </form>
                </div>
            </a>

            <p id="im">{% trans "I'm" %}</p>
            <a href="{% url 'business:business_signup' %}">
                <div id="business">
                    <img class="avatar-img" src="{% static 'beta_invite/img/business.png' %}">
                    <form id="business-form">
                        {% trans "Business" as business %}
                        <input id="business-input" type="button" value="{{ business }}">
                    </form>
                </div>
            </a>
        </div>
    </div>
{% endblock %}

testing_webpage/business/templates/business/start.html
{% extends 'peaku_base.html'%}
{% load static %}   <!-- Generates the absolute URL of static files-->
{% load i18n %}     <!--Django translation-->

{% block title %}{% trans "Personnel Selection - PeakU" %}{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'business/css/start.css' %}">
    <script type="text/javascript" src="{% static 'business/js/start.js' %}"></script>
    <script type="text/javascript" src="{% static 'business/js/preview_of_start.js' %}"></script>
    <script type="text/javascript" src="{% static 'business/js/add_bullets.js' %}"></script>
    <script type="text/javascript" src="{% static 'business/js/preview_helper.js' %}"></script>

    <!-- MailerLite Universal -->
    <script>
        (function(m,a,i,l,e,r){ m['MailerLiteObject']=e;function f(){
        var c={ a:arguments,q:[]};var r=this.push(c);return "number"!=typeof r?r:f.bind(c.q);}
        f.q=f.q||[];m[e]=m[e]||f.bind(f.q);m[e].q=m[e].q||f.q;r=a.createElement(i);
        var _=a.getElementsByTagName(i)[0];r.async=1;r.src=l+'?v'+(~~(new Date().getTime()/1000000));
        _.parentNode.insertBefore(r,_);})(window, document, 'script', 'https://static.mailerlite.com/js/universal.js', 'ml');
        var ml_account = ml('accounts', '1042996', 'o9s9l3m3p3', 'load');
    </script>
{% endblock %}

{% block content %}

    <h2 style="color:var(--brochure-blue); margin-left: 7%; margin-top: 3%;">Creación de campaña</h2>
    <h5 class="paragraph" align="center" style="margin-left: 7%; margin-right: 10%;">
        <p>Ingresa la información de la vacante y de la empresa, registrate y empieza
         a recibir aplicantes.</p>
        <p style="font-size: 18px;"> Todo en menos de diez minutos. ¡ Así de fácil !</p>
    </h5>

    <div class="tab">
        <button id="vacancy_button" class="tab-links active" onclick="tab(event, 'vacancy')" >Vacante</button>
        <button id="company_button" class="tab-links" onclick="tab(event, 'company')" disabled >{% trans "Company" %}</button>
        <button id="start_button" class="tab-links" onclick="tab(event, 'start')" disabled >Registro</button>
    </div>

    <form class="content" action="{% url 'business:start_post' %}" method="post">

        <div id="vacancy" class="tab-content">
            {% include "business/tab_vacancy.html" with requirement_bullet_id=requirement_bullet_id %}
        </div>

        <div id="company" class="tab-content">
            {% include "business/tab_company.html" with requirement_perk_id=requirement_perk_id %}
        </div>

        <div id="start" class="tab-content">
            {% include "business/tab_signup.html"%}
        </div>
    </form>

    <!-- After loading every element, sets the first element as active.-->
    <script type="text/javascript">
       activate_tab('vacancy');
    </script>
{% endblock %}